In [44]:
import cf_test_2_1 
reload(cf_test_2_1)

<module 'cf_test_2_1' from 'cf_test_2_1.py'>

In [2]:
import dataset
data = dataset.load_data(cv=0)

In [5]:
# reload(cf_test_2_1)
result = {}
def foo(knn):
    cf = cf_test_2_1.IBCF(knn=knn, sim='cosine',s=4, topk=5)
    cf.fit(train=data.train_dataset.train, X = data.train_dataset.train.T)
#     print('prediction')
    cf.predict(data.test_dataset.targets)
    r = cf.evaluate(test=data.test_dataset.test)
    result[knn] = r
    return (knn,r)

In [12]:
knn = 299
cf = cf_test_2_1.IBCF(knn=knn, sim='cosine',s=4, topk=5)
cf.fit(train=data.train_dataset.train, X = data.train_dataset.train.T)
#     print('prediction')
cf.predict(data.test_dataset.targets)
r = cf.evaluate(test=data.test_dataset.test)
result[knn] = r
print r


In [20]:
item_neighbor = cf.item_neighbors_.values()

In [22]:
item_neighbor = [j for i in item_neighbor for j in i]

TypeError: 'numpy.int64' object is not iterable

In [28]:
cf.recommendation_[16]

array([3701,   10,    9,    5,    0])

In [31]:
data.test_dataset.test[16,:].nonzero()

(array([  29,   74,  106,  157,  192,  216,  284,  291,  309,  310,  319,
         346,  432,  513,  515,  581,  610,  677,  689,  737,  810,  881,
        1050, 1052, 1091, 1124, 1192, 1245, 1275, 1297, 1324, 1406, 1453,
        1463, 1478, 1491, 1500, 1516, 1563, 1594, 1729, 1741, 1743, 1829,
        1831, 1936, 2096, 2097, 2128, 2214, 2262, 2307, 2338, 2347, 2357,
        2358, 2400, 2411, 2438, 2455, 2460, 2461, 2466, 2557, 2704, 2773,
        2794, 2818, 2855, 2898, 2940, 2958, 3022, 3032, 3043, 3045, 3074,
        3107, 3185, 3186, 3238, 3251, 3270, 3277, 3294, 3341, 3384, 3397,
        3416, 3420, 3454, 3457, 3459, 3460, 3462, 3503, 3508, 3550, 3680]),)

In [34]:
result

{100: (0.10894039735099337, 0.0084366867567188045),
 200: (0.10794701986754968, 0.0082819880441935018),
 299: (0.1052980132450331, 0.0082400854637090463),
 300: (0.10496688741721853, 0.008189914883737142),
 400: (0.10695364238410596, 0.0082572925166338514),
 500: (0.10463576158940398, 0.0082352796892300462)}

In [4]:
import multiprocessing
p = multiprocessing.Pool(5)
p.map(foo,[100,200,300,400,500])

/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_j

prediction
prediction
prediction
prediction
prediction


[None, None, None, None, None]

Process PoolWorker-5:
Traceback (most recent call last):
Process PoolWorker-1:
Traceback (most recent call last):
Process PoolWorker-3:
Process PoolWorker-2:
Process PoolWorker-4:
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
    self.run()
    self.run()
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/lanxiang/miniconda2/lib/python2.7/multipro

In [35]:
map(foo,[1000,2000,3000])

[None, None, None]

In [8]:
foo(299)

In [36]:
result

{100: (0.10894039735099337, 0.0084366867567188045),
 200: (0.10794701986754968, 0.0082819880441935018),
 299: (0.1052980132450331, 0.0082400854637090463),
 300: (0.10496688741721853, 0.008189914883737142),
 400: (0.10695364238410596, 0.0082572925166338514),
 500: (0.10463576158940398, 0.0082352796892300462),
 1000: (0.09238410596026489, 0.0070502652040447828),
 2000: (0.0880794701986755, 0.0067772694490778026),
 3000: (0.085099337748344356, 0.0065860756152155133)}

In [39]:
knn = 299
cf = cf_test_2_1.IBCF(knn=knn, sim='asymcos',s=4, topk=5)
cf.fit(train=data.train_dataset.train, X = data.train_dataset.train.T)
#     print('prediction')
cf.predict(data.test_dataset.targets)
r = cf.evaluate(test=data.test_dataset.test)
result[knn] = r
print r


(0.021854304635761591, 0.0016701536668641951)


In [40]:
knn = 299
cf = cf_test_2_1.IBCF(knn=knn, sim='dot',s=4, topk=5)
cf.fit(train=data.train_dataset.train, X = data.train_dataset.train.T)
#     print('prediction')
cf.predict(data.test_dataset.targets)
r = cf.evaluate(test=data.test_dataset.test)
result[knn] = r
print r


(0.094370860927152314, 0.006960131249638353)


In [40]:
knn = 299
cf = cf_test_2_1.IBCF(knn=knn, sim='dot',s=4, topk=5)
cf.fit(train=data.train_dataset.train, X = data.train_dataset.train.T)
#     print('prediction')
cf.predict(data.test_dataset.targets)
r = cf.evaluate(test=data.test_dataset.test)
result[knn] = r
print r


(0.094370860927152314, 0.006960131249638353)


In [70]:
knn = 100
cf = cf_test_2_1.IBCF(knn=knn, sim='dot',s=-1, topk=5)
cf.fit(train=data.train_dataset.train, X = data.train_dataset.train.T)
#     print('prediction')
cf.predict(data.test_dataset.targets)
r = cf.evaluate(test=data.test_dataset.test)
result[knn] = r
print r


(0.09602649006622517, 0.0071196275889972111)


In [59]:
a = cf.prediction_.copy()
ar = cf.recommendation_.copy()

In [61]:
ar

{16: array([3701,    6,    5,    2,    0]),
 18: array([   5, 3702,    4,    2, 3705]),
 34: array([3701,    9,    5,    2,    0]),
 44: array([3701,    6,    5,    4,    0]),
 50: array([3701, 3702,    4,    2, 3705]),
 52: array([3701,    6,    5,    2,    0]),
 61: array([3701,    9,    5,    2,    0]),
 75: array([3701, 3702,    3,    2, 3705]),
 76: array([3701,    6,    5,    2,    0]),
 98: array([   5, 3702,    4,    2, 3705]),
 106: array([3701,    6,    5,    2,    0]),
 113: array([3701,    5,    4,    2, 1852]),
 118: array([3701, 3702,    4,    2, 3705]),
 119: array([3701,    6,    5,    2,    0]),
 124: array([9, 6, 5, 2, 0]),
 126: array([3701, 3702,    4,    2,    0]),
 164: array([3701,    6,    5,    2,    0]),
 170: array([3701,    6,    5,    2,    0]),
 175: array([6, 5, 4, 2, 0]),
 183: array([3701,    5,    4,    2, 3705]),
 195: array([9, 6, 5, 2, 0]),
 204: array([3701,    6,    5,    2,    0]),
 236: array([3701, 3702,    5,    2, 3705]),
 242: array([3701, 3

In [67]:
import copy

In [69]:
a = copy.deepcopy(cf)

In [73]:
a

<cf_test_2_1.IBCF instance at 0x7fdfb4c87248>

In [75]:
b = copy.deepcopy(cf)

In [77]:
b

<cf_test_2_1.IBCF instance at 0x7fdfb4c42320>

In [82]:
(a.prediction_ == b.prediction_).all()

False

In [47]:
cf.similarities_

array([[   0.,  456.,  258., ...,   31.,    0.,  162.],
       [ 456.,    0.,  140., ...,    0.,    0.,   66.],
       [ 258.,  140.,    0., ...,    0.,    0.,   48.],
       ..., 
       [  31.,    0.,    0., ...,    0.,    0.,   33.],
       [   0.,    0.,    0., ...,    0.,    0.,   23.],
       [ 162.,   66.,   48., ...,   33.,   23.,    0.]])

In [54]:
for i in xrange(3706):
    for j in xrange(3706):
        if cf.count[i,j] == 0 and cf.similarities_[i,j] != 0:
            print (cf.similarities_[i,j])


In [178]:
sum(data.train_dataset.train[data.test_dataset.targets,:])

array([ 112.,   38.,   28., ...,    1.,    3.,   20.], dtype=float32)

20170919

In [88]:
import cf_test_2_1 as cf21

In [90]:
import dataset
cv = 0
data = dataset.load_data(cv)

In [119]:
cf_models = {}
for k in [50, 100, 200, 500, 1000]:
    cf = cf21.IBCF(knn=k, s=0, sim='cosine',topk=10)
    cf.fit(train=data.train_dataset.train,X = data.train_dataset.train.T)
    cf.predict(data.test_dataset.targets)
    cf_models[k] = cf
    print k, cf.evaluate(test=data.test_dataset.test)

50 (0.10976821192052982, 0.016037094453690396)
100 (0.10711920529801325, 0.016670186462586604)
200 (0.1052980132450331, 0.015723285225252324)
500 (0.10033112582781459, 0.01425124536318576)
1000 (0.086092715231788075, 0.012283572627969712)


In [121]:
for k in [10,20, 30, 40]:
    cf = cf21.IBCF(knn=k, s=0, sim='cosine',topk=10)
    cf.fit(train=data.train_dataset.train,X = data.train_dataset.train.T)
    cf.predict(data.test_dataset.targets)
    cf_models[k] = cf
    print k, cf.evaluate(test=data.test_dataset.test)

10 (0.084768211920529801, 0.011572751858233296)
20 (0.096688741721854307, 0.013834699871558718)
30 (0.10231788079470198, 0.014275365396021301)
40 (0.1064569536423841, 0.015300484298222956)


In [124]:
cf_models2 = {}

for k in [10,20, 30, 40]:
    cf = cf21.IBCF(knn=k, s=4, sim='cosine',topk=10)
    cf.fit(train=data.train_dataset.train,X = data.train_dataset.train.T)
    cf.predict(data.test_dataset.targets)
    cf_models2[k] = cf
    print k, cf.evaluate(test=data.test_dataset.test)

10 (0.084768211920529801, 0.011776780908092407)
20 (0.095198675496688742, 0.013735806758567644)
30 (0.099999999999999992, 0.014079252364226894)
40 (0.10413907284768213, 0.015107891181109867)


In [ ]:
cf_models = {}
for k in [50, 100, 200, 500, 1000]:
    cf = cf21.IBCF(knn=k, s=0, sim='cosine',topk=10)
    cf.fit(train=data.train_dataset.train,X = data.train_dataset.train.T)
    cf.predict(data.test_dataset.targets)
    cf_models[k] = cf
    print k, cf.evaluate(test=data.test_dataset.test)

In [125]:
a = cf_models[50]
print a

<cf_test_2_1.IBCF instance at 0x7fdfbf8d8710>


In [127]:
b = cf_models[500]
print b

<cf_test_2_1.IBCF instance at 0x7fdfb396c5f0>


In [128]:
a.item_neighbors_

{0: array([ 106, 1199, 1295, 1384, 1148, 1900, 2426,  858, 1215,  357,   38,
        1993, 2710, 1059,  287, 2128,  593, 1618,  466, 2651, 1504,  579,
        1120, 1108, 1107, 1106, 2374, 3029, 2203, 1025,   33, 2162,  253,
        2511,  309, 2557,  346, 1449,  354, 2592, 2898,  443, 1848, 1743,
        1178,  581,  574, 1173,  575, 1398]),
 1: array([2708,  319,    0,  737,  202,  745, 1003, 1025,  702,  699, 1278,
        1292, 1406, 1420, 1428,  651, 1449,  354,  152,  147, 1561, 1737,
        1740, 1787, 1825, 1832, 1873, 3256,  632, 1919, 1924,   58, 1934,
         627, 1962, 1980, 1993, 2012,  572, 3206,  466,  370, 2415, 2426,
           9,  357,  307, 2592,  308, 1539]),
 2: array([3031, 3024,  799,  229,  426, 3019,  702, 3623,  245,  688, 1294,
         346,  745,  741, 2745, 1278, 2099,  418, 3030,  269, 3023,  406,
        3033, 1613, 2142, 1352,  583,  360, 1371,  525, 1449,  224,  486,
         573,  572, 1420,  510, 1307, 2587,  147, 1714, 2231,  506,  329,
         34

In [136]:
(set(b.item_neighbors_[0]) - set(a.item_neighbors_[0]))

{1,
 5,
 9,
 10,
 16,
 20,
 24,
 31,
 35,
 44,
 46,
 47,
 49,
 60,
 68,
 92,
 101,
 107,
 108,
 136,
 144,
 147,
 155,
 159,
 174,
 179,
 202,
 210,
 216,
 224,
 228,
 239,
 246,
 279,
 283,
 284,
 291,
 307,
 308,
 319,
 323,
 327,
 329,
 334,
 339,
 343,
 347,
 358,
 362,
 367,
 370,
 396,
 420,
 421,
 426,
 427,
 428,
 440,
 452,
 457,
 460,
 471,
 483,
 486,
 494,
 506,
 513,
 515,
 525,
 527,
 529,
 537,
 538,
 539,
 541,
 571,
 572,
 573,
 576,
 578,
 580,
 582,
 583,
 627,
 632,
 639,
 651,
 678,
 689,
 699,
 702,
 708,
 713,
 735,
 737,
 740,
 741,
 742,
 745,
 780,
 799,
 802,
 838,
 842,
 843,
 847,
 849,
 851,
 859,
 862,
 863,
 892,
 955,
 957,
 960,
 963,
 964,
 967,
 970,
 971,
 972,
 977,
 992,
 1003,
 1007,
 1008,
 1016,
 1017,
 1018,
 1020,
 1022,
 1029,
 1050,
 1052,
 1066,
 1091,
 1094,
 1099,
 1104,
 1109,
 1110,
 1111,
 1116,
 1117,
 1118,
 1123,
 1124,
 1125,
 1129,
 1130,
 1131,
 1132,
 1133,
 1135,
 1139,
 1140,
 1143,
 1144,
 1150,
 1154,
 1155,
 1158,
 1160,
 

In [137]:
a.knn

50

In [114]:
a.rec_length

10

In [116]:
a.num_neighbor

50

In [138]:
b.num_neighbor

500

In [147]:
np.unique(data.test_dataset.test.nonzero()[0]) == data.test_dataset.targets

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [151]:
a.prediction_[6039,0]

9.4049206

In [153]:
a.train[6039,:]

array([ 0.,  0.,  0., ...,  0.,  0.,  0.], dtype=float32)

In [155]:
a.similarities_[0]

array([ 0.        ,  0.39991647,  0.27403855, ...,  0.09707808,
        0.04339206,  0.19070071])

In [159]:
nei = a.item_neighbors_[0]
nei

array([ 106, 1199, 1295, 1384, 1148, 1900, 2426,  858, 1215,  357,   38,
       1993, 2710, 1059,  287, 2128,  593, 1618,  466, 2651, 1504,  579,
       1120, 1108, 1107, 1106, 2374, 3029, 2203, 1025,   33, 2162,  253,
       2511,  309, 2557,  346, 1449,  354, 2592, 2898,  443, 1848, 1743,
       1178,  581,  574, 1173,  575, 1398])

In [170]:
a.similarities_[0,nei]

array([ 0.48764223,  0.48995769,  0.49245995,  0.49246001,  0.49282867,
        0.49412715,  0.49700773,  0.49435401,  0.49558944,  0.5024727 ,
        0.50389725,  0.50871992,  0.51360208,  0.51301515,  0.51259023,
        0.50881732,  0.51144379,  0.50959915,  0.51298165,  0.51225817,
        0.51208317,  0.51371568,  0.51965427,  0.51968408,  0.54064745,
        0.54397601,  0.55046058,  0.51575881,  0.54116136,  0.51550871,
        0.56388289,  0.56265646,  0.54347032,  0.51494753,  0.5213455 ,
        0.51751173,  0.55780953,  0.55118567,  0.5357765 ,  0.5221892 ,
        0.59510905,  0.51957172,  0.52081472,  0.53862226,  0.55807668,
        0.52058244,  0.59038794,  0.60831612,  0.5186218 ,  0.52652311])

In [163]:
a.train[6039,nei]

array([ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,
        0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.], dtype=float32)

In [164]:
a.similarities_[0,nei].dot(a.train[6039,nei])

9.4049204587936401

In [167]:
x  =[ 0.48764223,  0.48995769,  0.49245995,  0.49246001,  0.49282867,
        0.49412715,  0.49700773,  0.49435401,  0.49558944,  0.5024727 ,
        0.50389725,  0.50871992,  0.51360208,  0.51301515,  0.51259023,
        0.50881732,  0.51144379,  0.50959915,  0.51298165,  0.51225817,
        0.51208317,  0.51371568,  0.51965427,  0.51968408,  0.54064745,
        0.54397601,  0.55046058,  0.51575881,  0.54116136,  0.51550871,
        0.56388289,  0.56265646,  0.54347032,  0.51494753,  0.5213455 ,
        0.51751173,  0.55780953,  0.55118567,  0.5357765 ,  0.5221892 ,
        0.59510905,  0.51957172,  0.52081472,  0.53862226,  0.55807668,
        0.52058244,  0.59038794,  0.60831612,  0.5186218 ,  0.52652311]

In [172]:
y = [ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,
        0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.]

In [174]:
r=0
for m,n in zip(x,y):
    r += m*n
print r

9.40492045


In [182]:
import dataset2
data2 = dataset2.load_data(1)

In [259]:
import cf_test_2_1 as cf21
reload(cf21)


<module 'cf_test_2_1' from 'cf_test_2_1.py'>

In [264]:

cf_models = {}
# for k in [130]:
for k in [50, 100, 200, 500, 1000]:
    cf = cf21.IBCF(knn=k, s=0, sim='cosine',topk=10)
    cf.fit(train=data2.train_dataset.train,X = data2.train_dataset.train.T)
    cf.predict(data2.test_dataset.targets, input_data=data2.train_dataset.newusers)
    cf_models[k] = cf
    print k, cf.evaluate(test=data2.test_dataset.test)

50 (0.3566225165562914, 0.080691918491222286)
100 (0.36605960264900667, 0.081341822243258977)
200 (0.37235099337748345, 0.085444045574155789)
500 (0.37533112582781453, 0.087184865215529816)
1000 (0.3698675496688742, 0.085912290610198866)


In [266]:

cf_models2 = {}
# for k in [130]:
for k in [50, 100, 200, 500, 1000]:
    cf = cf21.IBCF(knn=k, s=0, sim='cosine',topk=5)
    cf.fit(train=data2.train_dataset.train,X = data2.train_dataset.train.T)
    cf.predict(data2.test_dataset.targets, input_data=data2.train_dataset.newusers)
    cf_models2[k] = cf
    print k, cf.evaluate(test=data2.test_dataset.test)

50 (0.39205298013245032, 0.046014118509787039)
100 (0.40695364238410597, 0.047395676789706936)
200 (0.40364238410596026, 0.048862139786596009)
500 (0.42980132450331132, 0.052606626810292476)
1000 (0.4258278145695365, 0.05195173880273736)


In [265]:
cf.user_perf

{8: (0.4, 0.07547169811320754),
 27: (0.5, 0.09259259259259259),
 55: (0.9, 0.2647058823529412),
 84: (0.2, 0.1),
 91: (0.5, 0.023255813953488372),
 110: (0.6, 0.13043478260869565),
 113: (0.3, 0.061224489795918366),
 141: (0.5, 0.20833333333333334),
 144: (0.4, 0.2),
 146: (0.5, 0.05319148936170213),
 177: (0.2, 0.034482758620689655),
 178: (0.7, 0.12727272727272726),
 204: (0.2, 0.025974025974025976),
 205: (0.3, 0.2),
 217: (0.3, 0.06976744186046512),
 224: (0.7, 0.027559055118110236),
 232: (0.3, 0.1111111111111111),
 253: (0.2, 0.16666666666666666),
 274: (0.6, 0.13333333333333333),
 275: (0.3, 0.25),
 286: (0.6, 0.11538461538461539),
 324: (0.2, 0.09090909090909091),
 362: (0.2, 0.09090909090909091),
 381: (0.4, 0.14285714285714285),
 397: (0.7, 0.061946902654867256),
 416: (0.0, 0.0),
 426: (0.2, 0.14285714285714285),
 434: (0.8, 0.12121212121212122),
 435: (0.8, 0.11940298507462686),
 436: (0.2, 0.07692307692307693),
 437: (0.8, 0.026578073089700997),
 440: (0.4, 0.166666666666

In [252]:
cf.user_perf[8]

KeyError: 8

In [235]:
cf = cf_models[100]

In [236]:
cf.item_neighbors_[0]


array([ 496, 1366, 2222,  724, 1491, 2530, 1015,  436, 1258, 1943, 2735,
       1720, 1262,  220,  148,  547, 3106, 2631, 1372,  353,  583,  588,
       2233, 1543, 1196,   31, 1182, 3352,  642, 2012, 1656, 1239,  770,
        523, 1575, 1568, 2918,  108, 2928,  586, 1271, 1023, 1058, 1063,
         49, 2722, 1899, 1931,  376, 1287,  373,   20, 2847, 2502,  257,
       1959,  293,  315,  352,  360,  363,  453,  476, 1854, 2647, 2105,
        584, 2559,  585,  589,  591,  604, 3045, 2789,  907, 1595, 2693,
       1539, 1482,   38, 2252,   33, 1468, 2327, 1081, 3184, 3186, 1120,
       1178, 1179, 1180, 1192, 2728, 1373, 1220, 1245, 1250, 2849, 2286,
       1726])

In [237]:
data2.test_dataset.targets

array([   8,   27,   55,   84,   91,  110,  113,  141,  144,  146,  177,
        178,  204,  205,  217,  224,  232,  253,  274,  275,  286,  324,
        362,  381,  397,  416,  426,  434,  435,  436,  437,  440,  445,
        461,  465,  472,  482,  498,  511,  515,  554,  560,  570,  571,
        606,  634,  640,  645,  650,  652,  658,  661,  671,  672,  688,
        691,  716,  731,  748,  754,  755,  782,  785,  788,  811,  812,
        832,  837,  851,  868,  907,  908,  909,  921,  922,  949,  953,
        954,  959,  969,  974,  977,  981,  992,  994,  999, 1017, 1048,
       1073, 1081, 1084, 1109, 1120, 1147, 1152, 1161, 1164, 1165, 1184,
       1189, 1191, 1207, 1208, 1209, 1211, 1217, 1223, 1251, 1252, 1263,
       1273, 1285, 1291, 1297, 1299, 1309, 1318, 1329, 1334, 1337, 1339,
       1368, 1377, 1392, 1396, 1411, 1423, 1428, 1430, 1444, 1447, 1450,
       1451, 1455, 1457, 1461, 1462, 1465, 1466, 1484, 1490, 1500, 1508,
       1518, 1520, 1537, 1547, 1549, 1555, 1557, 15

In [238]:
cf.prediction_[8,:]

array([ 9.81667423,  2.95129418,  2.65628934, ...,  0.73898   ,
        0.14191246,  5.92825699], dtype=float32)

In [239]:
sum(data2.test_dataset.test[8,:])

53.0

In [218]:
sum(data2.train_dataset.newusers[8,:])

53.0

In [240]:
cf.recommendation_[8]

array([ 352, 2222,  293, 1636, 2693, 1195, 1245, 1372, 1656,  315])

In [241]:
data2.test_dataset.test[8,:].nonzero()[0]

array([  15,   24,  315,  345,  408,  424,  476,  604,  768,  827,  900,
        908,  982, 1046, 1073, 1132, 1192, 1195, 1203, 1205, 1214, 1287,
       1290, 1335, 1337, 1421, 1468, 1543, 1607, 1623, 1672, 1892, 1959,
       2097, 2233, 2255, 2530, 2623, 2693, 2821, 2890, 3045, 3109, 3184,
       3186, 3201, 3339, 3415, 3554, 3682, 3686, 3756, 3846])

In [242]:
set(cf.recommendation_[8]).intersection(set(data2.test_dataset.test[8,:].nonzero()[0]))

{315, 1195, 2693}

In [243]:
cf.user_perf.keys()

[2946,
 4356,
 3316,
 3079,
 3543,
 652,
 1165,
 782,
 2831,
 3728,
 785,
 2322,
 1299,
 3989,
 2329,
 921,
 2460,
 1184,
 3749,
 1705,
 6023,
 812,
 3758,
 5960,
 5875,
 5300,
 3401,
 1465,
 3842,
 3260,
 5696,
 4384,
 3269,
 5319,
 2892,
 2505,
 3786,
 204,
 4046,
 1677,
 4494,
 953,
 4568,
 2276,
 1755,
 2909,
 2654,
 5669,
 1252,
 3980,
 2029,
 2416,
 113,
 275,
 1396,
 1273,
 2170,
 4476,
 253]

In [245]:
y_true = data2.test_dataset.test[8].nonzero()[0]
y_true

array([  15,   24,  315,  345,  408,  424,  476,  604,  768,  827,  900,
        908,  982, 1046, 1073, 1132, 1192, 1195, 1203, 1205, 1214, 1287,
       1290, 1335, 1337, 1421, 1468, 1543, 1607, 1623, 1672, 1892, 1959,
       2097, 2233, 2255, 2530, 2623, 2693, 2821, 2890, 3045, 3109, 3184,
       3186, 3201, 3339, 3415, 3554, 3682, 3686, 3756, 3846])

In [246]:
cf.user_perf[8]

KeyError: 8

In [96]:
cf.predict(data.test_dataset.targets)

<cf_test_2_1.IBCF instance at 0x7fdfb67757a0>

In [97]:
cf.evaluate(test=data.test_dataset.test)

(0.091225165562913921, 0.1454494505334869)

sample negative

In [ ]:
class Net(nn.Module):
    def __init__(input_size, hidden_size, output_size):
        self.encoder = nn.h

In [269]:
import torch
from torch import nn

20170922

In [2]:
import numpy as np
class Rec():
    def __init__(self, rec_len):
        self.rec_len = rec_len
    def set_prediction_matrix(self, prediction_matrix):
        '''

        :param prediction_matrix: user*item
        :return:
        '''
        self.prediction_matrix = prediction_matrix
        self.item_num = self.prediction_matrix.shape[1]

        return self
    def produce_rec_list(self, targets):
        self.targets = targets
        self.recommendation_ = dict()
        for user in targets:
            # find the disordered recommendation list
            disorder = np.argpartition(self.prediction_matrix[user, :], self.item_num - self.rec_len)[
                       -1 * self.rec_len:]
            # order the recomendataion list, descending order
            # import pdb; pdb.set_trace();
            # self.recommendation_[user] = np.argsort(-1 * self.prediction_[user,disorder])
            self.recommendation_[user] = disorder
        return self
    def evaluate(self, test):
        '''

                :param test: user*item
                :return: self
                '''
        self.user_perf = dict()
        self.test = test
        for u in self.targets:
            y_true = test[u].nonzero()[0]
            # if u == 8: print ('\n',u,y_true )
            # if len(y_true) == 0: continue

            y_pred = self.recommendation_[u]
            right_rec = len(set(y_true).intersection(set(y_pred))) * 1.0
            precision = right_rec / self.rec_len
            # if user has no rating in test set, ignor him
            recall = right_rec / len(y_true)
            self.user_perf[u] = (precision, recall)
        self.precision_ = np.average([i[0] for i in self.user_perf.values()])
        self.recall_ = np.average([i[1] for i in self.user_perf.values()])
        return self.precision_, self.recall_


    

In [6]:
import dataset2
data = dataset2.load_data(1)

In [7]:
import numpy as np
rand_mtx = np.random.random(data.train_dataset.train.shape)

In [52]:
recp = Rec(rec_len=5)
recp.set_prediction_matrix(rand_mtx)
recp.produce_rec_list(data.test_dataset.targets)
recp.evaluate(data.test_dataset.test)

TypeError: __init__() got an unexpected keyword argument 'rec_len'

In [88]:
import numpy as np
class RecS():
    def __init__(self, rec_len):
        self.rec_len = rec_len
    def set_prediction_matrix(self, prediction_matrix):
        '''

        :param prediction_matrix: user*item
        :return:
        '''
        self.prediction_matrix = prediction_matrix
        self.item_num = self.prediction_matrix.shape[1]

        return self
    def produce_rec_list(self, targets):
        self.targets = targets
        self.recommendation_ = dict()
        for user in targets:
            # find the disordered recommendation list
            disorder_idx = np.argsort(self.prediction_matrix[user, :])[
                       -1 * self.rec_len:]
            # order the recomendataion list, descending order
            # import pdb; pdb.set_trace();
            tmp = np.argsort(-1 * self.prediction_[user,disorder_idx])
            self.recommendation_[user] = list(reversed( disorder_idx[tmp] ))
        return self
    def evaluate(self, test):
        '''

                :param test: user*item
                :return: self
                '''
        self.user_perf = dict()
        self.test = test
        for u in self.targets:
            y_true = test[u].nonzero()[0]
            # if u == 8: print ('\n',u,y_true )
            # if len(y_true) == 0: continue

            y_pred = self.recommendation_[u]
            right_rec = len(set(y_true).intersection(set(y_pred))) * 1.0
            precision = right_rec / self.rec_len
            # if user has no rating in test set, ignor him
            recall = right_rec / len(y_true)
            self.user_perf[u] = (precision, recall)
        self.precision_ = np.average([i[0] for i in self.user_perf.values()])
        self.recall_ = np.average([i[1] for i in self.user_perf.values()])
        return self.precision_, self.recall_


    

In [51]:
recs = RecS(rec_len=5)
recs.set_prediction_matrix(rand_mtx)
recs.produce_rec_list(data.test_dataset.targets)
recs.evaluate(data.test_dataset.test)

(0.018543046357615899, 0.00098077254627308079)

In [14]:
reclist_p = recp.recommendation_
reclist_s = recs.recommendation_

In [78]:
for u in data.test_dataset.targets:
    flag = set(reclist_p[u]) == set(reclist_s[u])
    print('for user %s, it is %s'%(u, (flag)))

for user 8, it is True
for user 27, it is True
for user 55, it is True
for user 84, it is True
for user 91, it is True
for user 110, it is True
for user 113, it is True
for user 141, it is True
for user 144, it is True
for user 146, it is True
for user 177, it is True
for user 178, it is True
for user 204, it is True
for user 205, it is True
for user 217, it is True
for user 224, it is True
for user 232, it is True
for user 253, it is True
for user 274, it is True
for user 275, it is True
for user 286, it is True
for user 324, it is True
for user 362, it is True
for user 381, it is True
for user 397, it is True
for user 416, it is True
for user 426, it is True
for user 434, it is True
for user 435, it is True
for user 436, it is True
for user 437, it is True
for user 440, it is True
for user 445, it is True
for user 461, it is True
for user 465, it is True
for user 472, it is True
for user 482, it is True
for user 498, it is True
for user 511, it is True
for user 515, it is True
for us

In [18]:
a = rand_mtx[0,10:20]*10
a

array([ 4.20523656,  3.85367247,  0.21137906,  2.52858853,  0.56531778,
        1.05805927,  0.64699903,  1.54162346,  0.42795672,  9.41074581])

In [25]:
tmp2 = np.argsort(a)[-6:]
tmp2

array([5, 7, 3, 1, 0, 9])

In [31]:
tmp = np.argpartition(a,4)[-6:]
tmp

array([5, 7, 1, 3, 0, 9])

In [32]:
tmp[np.argsort(a[tmp])]

array([5, 7, 3, 1, 0, 9])

In [26]:
a[tmp2]

array([ 1.05805927,  1.54162346,  2.52858853,  3.85367247,  4.20523656,
        9.41074581])

In [42]:
list(reversed(a[tmp]))[:2]

[9.4107458057832414, 4.205236563042841]

In [29]:
np.argsort(a[[2,4]])

array([0, 1])

In [36]:
mtx = np.random.random((3,5)) *10
mtx 

array([[ 7.46834233,  1.58019897,  4.75676504,  7.1232255 ,  8.64779742],
       [ 8.19736674,  8.27201483,  4.45901107,  7.74565248,  8.91727127],
       [ 1.11858432,  1.01120727,  1.03653477,  2.38055907,  5.32555262]])

In [89]:
import numpy as np
class Rec():
    def __init__(self):
        self.default_rec_len = 50
    def set_prediction_matrix(self, prediction_matrix):
        '''

        :param prediction_matrix: user*item
        :return:
        '''
        self.prediction_matrix = prediction_matrix
        self.item_num = self.prediction_matrix.shape[1]

        return self
    def produce_rec_list(self, targets):
        self.targets = targets
        self.recommendation_ = dict()
        for user in targets:
            # find the disordered recommendation list
            disorder_idx = np.argpartition(self.prediction_matrix[user, :], self.item_num - self.default_rec_len)[
                       -1 * self.default_rec_len:]
            # order the recomendataion list, descending order
            # import pdb; pdb.set_trace();
            tmp = np.argsort(-1 * self.prediction_matrix[user,disorder_idx])
            self.recommendation_[user] = list(( disorder_idx[tmp] ))
        return self
    def evaluate(self, test, rec_len):
        '''

                :param test: user*item
                :return: self
                '''
        if rec_len > self.default_rec_len:
            raise AttributeError("rec_len > default_rec_len." )

        self.rec_len = rec_len

        self.user_perf = dict()
        self.test = test
        for u in self.targets:
            y_true = test[u].nonzero()[0]
            # if u == 8: print ('\n',u,y_true )
            # if len(y_true) == 0: continue

            y_pred = self.recommendation_[u][:self.rec_len]
            right_rec = len(set(y_true).intersection(set(y_pred))) * 1.0
            precision = right_rec / self.default_rec_len
            # if user has no rating in test set, ignor him
            recall = right_rec / len(y_true)
            self.user_perf[u] = (precision, recall)
        self.precision_ = np.average([i[0] for i in self.user_perf.values()])
        self.recall_ = np.average([i[1] for i in self.user_perf.values()])
        return self.precision_, self.recall_



In [90]:
r = Rec()
r.set_prediction_matrix(rand_mtx)
r.produce_rec_list(data.test_dataset.targets)
r.evaluate(data.test_dataset.test,5)

(0.0018543046357615896, 0.00098077254627308079)

In [73]:
recs = RecS(rec_len=5)
recs.set_prediction_matrix(rand_mtx)
recs.produce_rec_list(data.test_dataset.targets)
recs.evaluate(data.test_dataset.test)

(0.018543046357615899, 0.00098077254627308079)

In [75]:
reclist_ps = r.recommendation_
reclist_s = recs.recommendation_

In [80]:
for u in data.test_dataset.targets:
    flag = set(reclist_ps[u][:5]) == set(reclist_s[u])
    
    print('for user %s, it is %s'%(u, (flag)))
    

for user 8, it is False
for user 27, it is False
for user 55, it is False
for user 84, it is False
for user 91, it is False
for user 110, it is False
for user 113, it is False
for user 141, it is False
for user 144, it is False
for user 146, it is False
for user 177, it is False
for user 178, it is False
for user 204, it is False
for user 205, it is False
for user 217, it is False
for user 224, it is False
for user 232, it is False
for user 253, it is False
for user 274, it is False
for user 275, it is False
for user 286, it is False
for user 324, it is False
for user 362, it is False
for user 381, it is False
for user 397, it is False
for user 416, it is False
for user 426, it is False
for user 434, it is False
for user 435, it is False
for user 436, it is False
for user 437, it is False
for user 440, it is False
for user 445, it is False
for user 461, it is False
for user 465, it is False
for user 472, it is False
for user 482, it is False
for user 498, it is False
for user 511, it i

In [81]:
r.recommendation_[8]

[2994,
 528,
 2719,
 872,
 260,
 2484,
 146,
 688,
 1540,
 107,
 1490,
 3278,
 756,
 2038,
 2039,
 383,
 3548,
 3480,
 1686,
 486,
 3635,
 362,
 540,
 3070,
 569,
 14,
 1285,
 3583,
 2134,
 1761,
 1988,
 2175,
 2048,
 2302,
 305,
 470,
 1634,
 299,
 1584,
 53,
 508,
 2309,
 3554,
 3361,
 727,
 150,
 3880,
 2280,
 772,
 3353]

In [82]:
recs.recommendation_[8]

array([ 150, 3880, 2280,  772, 3353])

In [87]:
r.prediction_matrix[8,r.recommendation_[8]] == sorted(r.prediction_matrix[8,r.recommendation_[8]])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True], dtype=bool)

In [72]:
set([r, recs]) == set([recs])

False

In [93]:
a = {1:1,3:3,5:5}
a

{1: 1, 3: 3, 5: 5}

In [94]:
b= np.array([1,3])
b

array([1, 3])

In [96]:
a[list(b)]

TypeError: unhashable type: 'list'

In [127]:
import rec3
reload(rec3)
cf = rec3.IBCF(sim='cosine', topN=100)
cf.fit(data.train_dataset.train, profile=data.train_dataset.train.T)
# cf.

NameError: name 'data' is not defined

20170925

In [157]:
import dataset2
data2 = dataset2.load_data(1)

In [241]:
import rec3
reload(rec3)
# candinate
rec = rec3.IBCF(sim='cosine',topN=100)
rec.fit(train_ratings=data2.train_dataset.train.astype(np.float64), profile=data2.train_dataset.train.T.astype(np.float64))
rec.compute_score(data2.test_dataset.targets)
rec.produce_reclist(data2.test_dataset.targets)
rec.evaluate(test=data2.test_dataset.test,rec_len=5)
import numpy as np

In [243]:
print rec.rec_.precision_

0.162913907285


In [253]:
import rec3
reload(rec3)
# non candinate
rec = rec3.IBCF(sim='cosine')
rec.fit(train_ratings=data2.train_dataset.train.astype(np.float64), profile=data2.train_dataset.train.T.astype(np.float64))
rec.compute_score(topN=100, targets=data2.test_dataset.targets)
rec.produce_reclist(data2.test_dataset.targets)
rec.evaluate(test=data2.test_dataset.test,rec_len=5)
# import numpy as np

(0.16291390728476823, 0.027702376669764297)

In [254]:
rec.compute_score(topN=130, targets=data2.test_dataset.targets)
rec.produce_reclist(data2.test_dataset.targets)
rec.evaluate(test=data2.test_dataset.test,rec_len=5)


(0.18178807947019868, 0.030066318340554055)

In [255]:
for n in [150, 200, 300, 400]:
    rec.compute_score(topN=n, targets=data2.test_dataset.targets)
    rec.produce_reclist(data2.test_dataset.targets)
    print n, rec.evaluate(test=data2.test_dataset.test,rec_len=5)


150 (0.19304635761589403, 0.032078875116410291)
200 (0.1923841059602649, 0.031631045372081591)
300 (0.20364238410596028, 0.033829977048445176)
400 (0.22450331125827819, 0.037027454279641818)


In [256]:
for n in [500, 600, 700, 800, 900]:
    rec.compute_score(topN=n, targets=data2.test_dataset.targets)
    rec.produce_reclist(data2.test_dataset.targets)
    print n, rec.evaluate(test=data2.test_dataset.test,rec_len=5)


500 (0.21589403973509935, 0.035318851188115626)
600 (0.22682119205298013, 0.035702417664489908)
700 (0.23443708609271521, 0.036462547794710802)
800 (0.23046357615894039, 0.035343284132732765)
900 (0.23741721854304632, 0.036695555885069939)


In [257]:
for n in [1000, 1200, 1500]:
    rec.compute_score(topN=n, targets=data2.test_dataset.targets)
    rec.produce_reclist(data2.test_dataset.targets)
    print n, rec.evaluate(test=data2.test_dataset.test,rec_len=5)


1000 (0.23675496688741721, 0.03663250315608526)
1200 (0.23807947019867551, 0.037725112737108851)
1500 (0.23841059602649006, 0.037159470856376282)


In [268]:
rec.predicted_score_[8,293]

22.818041305588242

In [270]:
import rec3
reload(rec3)
# non candinate
rec = rec3.IBCF(sim='cosine')
rec.fit(train_ratings=data2.train_dataset.train.astype(np.float64), profile=data2.train_dataset.train.T.astype(np.float64))
rec.compute_score(topN=500, targets=data2.test_dataset.targets)
rec.produce_reclist(data2.test_dataset.targets)
rec.evaluate(test=data2.test_dataset.test,rec_len=5)
# import numpy as np

(0.21589403973509935, 0.035318851188115626)

In [264]:
rec.predicted_score_[8,[293,
  604,
  315,
  1959,
  2693,
  589,
  1539,
  352,
  453,
  585,
  2502,
  1245,
  1656,
  476,
  49,
  108,
  2789,
  1178,
  373,
  2847,
  1372,
  1854,
  1575,
  1568,
  770,
  1195,
  1726,
  0,
  2327,
  1636,
  376,
  2928,
  2821,
  724,
  2222,
  1180,
  2199,
  3509,
  1533,
  31,
  257,
  642,
  523,
  46,
  38,
  1073,
  1482,
  1250,
  1468,
  1023]].max()

22.818041305588242

In [265]:
rec.train_ratings[8,0]

1.0

In [262]:
rec.predicted_score_[8,:].max()


22.818041305588242

In [245]:
%timeit rec.compute_similarity(rec.profile)

1 loop, best of 3: 3.68 s per loop


In [246]:
%timeit rec.find_neighbors()


1 loop, best of 3: 137 ms per loop


In [ ]:
%timeit 

In [234]:
for i in xrange(5,50):
    rec.rec_.default_rec_len = i
    print i, rec.evaluate(data2.test_dataset.test, rec_len=i)

5 (0.16291390728476823, 0.027702376669764297)
6 (0.16639072847682118, 0.033559896996445397)
7 (0.16887417218543044, 0.038789236985770331)
8 (0.17301324503311258, 0.044389911739808073)
9 (0.17236938925680648, 0.048949214237922978)
10 (0.17350993377483445, 0.053305361718166987)
11 (0.17609873570138471, 0.059122663854172842)
12 (0.17687637969094924, 0.064666447930063278)
13 (0.17944472745797249, 0.070058857679195022)
14 (0.18034531693472089, 0.074476062965528556)
15 (0.17969094922737305, 0.079064696080066249)
16 (0.1808774834437086, 0.083420258918025084)
17 (0.18056096610829764, 0.087646938161315177)
18 (0.18018763796909493, 0.091839707201320828)
19 (0.18098640641338443, 0.096457220369268848)
20 (0.18203642384105961, 0.10095881413001734)
21 (0.18188268684957426, 0.10512094622459411)
22 (0.18242022877784467, 0.10955635272354539)
23 (0.18247912467607255, 0.11387944627310195)
24 (0.18308498896247241, 0.11796578580761875)
25 (0.18384105960264899, 0.1226445204286553)
26 (0.18301069791136018, 0

In [161]:
rec.similarities_

array([[ 0.        ,  0.40666224,  0.28865837, ...,  0.09689232,
         0.0423571 ,  0.19123203],
       [ 0.40666224,  0.        ,  0.26592092, ...,  0.08342617,
         0.03039191,  0.13559782],
       [ 0.28865837,  0.26592092,  0.        , ...,  0.0754717 ,
         0.02199529,  0.11682753],
       ..., 
       [ 0.09689232,  0.08342617,  0.0754717 , ...,  0.        ,
         0.19795764,  0.24533782],
       [ 0.0423571 ,  0.03039191,  0.02199529, ...,  0.19795764,
         0.        ,  0.19611614],
       [ 0.19123203,  0.13559782,  0.11682753, ...,  0.24533782,
         0.19611614,  0.        ]])

In [162]:
rec.similarities_.shape

(3883, 3883)

In [163]:
rec.item_neighbors_

{0: array([ 584, 1854,  315, 3045,  293,  352, 1959,  360,  907, 3184,  363,
        2012, 1726, 3186, 2105,  770, 1081, 2928, 2918, 2252, 2286, 2849,
        1287, 2847,  453, 2327, 1271, 1120,  257, 2502, 1595, 2559, 1250,
          33,  476, 1245,  604, 2789,   38, 1568, 1539, 2728,  591, 1178,
        1179, 1468, 2693, 1180, 1482,  589, 2647,  585, 1192,  586, 1262,
        1058, 1063, 1373,  583, 1931, 2233, 3106,  588,   49,  376,   20,
        1220,  523,  108, 2722, 1656,  220,  373, 2735, 1543, 1023, 3352,
        1575, 1239, 1899,  642,   31,  724, 2222, 1258, 2631, 1182, 1372,
         353, 2337,  547, 3379, 2031,  436, 2011,  148, 1196, 2530,  593,
        1985]),
 1: array([ 770, 1505,  586,  585,  584,  583,  582, 3410, 2093,    9, 2092,
         591,  376, 2918, 2337,  373, 1654,  156,  451, 2728, 1491, 1271,
        2964, 2105, 1058, 2074, 2336, 1985,  363, 1539, 2071, 1370,  151,
        2899,  360, 1943, 3420, 1178, 2124, 1763,  727,  724, 1807,  257,
        2401,  6

In [164]:
rec.similarities_[0,[ 584, 1854,  315, 3045,  293,  352, 1959,  360,  907, 3184,  363,
        2012, 1726, 3186, 2105,  770, 1081, 2928, 2918, 2252, 2286, 2849,
        1287, 2847,  453, 2327, 1271, 1120,  257, 2502, 1595, 2559, 1250,
          33,  476, 1245,  604, 2789,   38, 1568, 1539, 2728,  591, 1178,
        1179, 1468, 2693, 1180, 1482,  589, 2647,  585, 1192,  586, 1262,
        1058, 1063, 1373,  583, 1931, 2233, 3106,  588,   49,  376,   20,
        1220,  523,  108, 2722, 1656,  220,  373, 2735, 1543, 1023, 3352,
        1575, 1239, 1899,  642,   31,  724, 2222, 1258, 2631, 1182, 1372,
         353, 2337,  547, 3379, 2031,  436, 2011,  148, 1196, 2530,  593,
        1985]]

array([ 0.6114389 ,  0.54231729,  0.51766335,  0.60121761,  0.53024898,
        0.55729237,  0.50642215,  0.5308651 ,  0.51180722,  0.52179576,
        0.49163318,  0.50537231,  0.50688186,  0.49663099,  0.50403799,
        0.49601499,  0.50717252,  0.4932485 ,  0.49022484,  0.49709448,
        0.5508215 ,  0.5172147 ,  0.49668918,  0.4899858 ,  0.5284934 ,
        0.53200272,  0.49536891,  0.52977276,  0.5532683 ,  0.54969841,
        0.51365078,  0.50171075,  0.56698076,  0.56153785,  0.52114793,
        0.62218519,  0.52417277,  0.52778641,  0.50489381,  0.48590373,
        0.55372854,  0.49952324,  0.5323996 ,  0.55625356,  0.55563111,
        0.49653707,  0.50103568,  0.53420278,  0.52298239,  0.53180891,
        0.50880411,  0.53552697,  0.51488237,  0.48497012,  0.4612594 ,
        0.47435599,  0.477023  ,  0.48495528,  0.47707155,  0.46744353,
        0.46428776,  0.46572821,  0.47908993,  0.47509056,  0.4827237 ,
        0.47146053,  0.4828201 ,  0.47392101,  0.47426229,  0.47

In [165]:
rec.similarities_[0,:].max()

0.622185194267032

<rec3.IBCF instance at 0x7f46188b84d0>

In [216]:
rec.predicted_score_

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [218]:
((rec.predicted_score_).nonzero())

(array([   8,    8,    8, ..., 6023, 6023, 6023]),
 array([   0,    1,    2, ..., 3823, 3827, 3878]))

In [192]:
r = rec.train_ratings[3891]
r

array([ 1.,  0.,  0., ...,  0.,  0.,  0.])

In [194]:
rec.item_neighbors_[1]

array([ 770, 1505,  586,  585,  584,  583,  582, 3410, 2093,    9, 2092,
        591,  376, 2918, 2337,  373, 1654,  156,  451, 2728, 1491, 1271,
       2964, 2105, 1058, 2074, 2336, 1985,  363, 1539, 2071, 1370,  151,
       2899,  360, 1943, 3420, 1178, 2124, 1763,  727,  724, 1807,  257,
       2401,  642, 2352,  588, 1630,  647, 1533, 2572, 2184, 2571,  313,
       2046,  314, 1513, 2559,   59, 2548, 1848,  206, 1351, 1851,  325,
       2036, 2225,  778,  667, 1898, 2502, 2031, 2025, 1356, 1937, 1111,
          0,  476, 3370, 3369, 1335, 1081, 1936, 1522, 2847, 2012, 1934,
       1375, 2018, 1349, 1942, 1192,  250,  438, 1952,  481, 1255, 3629,
        345])

In [196]:
r[[ 770, 1505,  586,  585,  584,  583,  582, 3410, 2093,    9, 2092,
        591,  376, 2918, 2337,  373, 1654,  156,  451, 2728, 1491, 1271,
       2964, 2105, 1058, 2074, 2336, 1985,  363, 1539, 2071, 1370,  151,
       2899,  360, 1943, 3420, 1178, 2124, 1763,  727,  724, 1807,  257,
       2401,  642, 2352,  588, 1630,  647, 1533, 2572, 2184, 2571,  313,
       2046,  314, 1513, 2559,   59, 2548, 1848,  206, 1351, 1851,  325,
       2036, 2225,  778,  667, 1898, 2502, 2031, 2025, 1356, 1937, 1111,
          0,  476, 3370, 3369, 1335, 1081, 1936, 1522, 2847, 2012, 1934,
       1375, 2018, 1349, 1942, 1192,  250,  438, 1952,  481, 1255, 3629,
        345]]

array([ 1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.])

In [200]:
r[[ 770, 1505,  586,  585,  584,  583,  582, 3410, 2093,    9, 2092,
        591,  376, 2918, 2337,  373, 1654,  156,  451, 2728, 1491, 1271,
       2964, 2105, 1058, 2074, 2336, 1985,  363, 1539, 2071, 1370,  151,
       2899,  360, 1943, 3420, 1178, 2124, 1763,  727,  724, 1807,  257,
       2401,  642, 2352,  588, 1630,  647, 1533, 2572, 2184, 2571,  313,
       2046,  314, 1513, 2559,   59, 2548, 1848,  206, 1351, 1851,  325,
       2036, 2225,  778,  667, 1898, 2502, 2031, 2025, 1356, 1937, 1111,
          0,  476, 3370, 3369, 1335, 1081, 1936, 1522, 2847, 2012, 1934,
       1375, 2018, 1349, 1942, 1192,  250,  438, 1952,  481, 1255, 3629,
        345]].dot(rec.similarities_[1,[ 770, 1505,  586,  585,  584,  583,  582, 3410, 2093,    9, 2092,
        591,  376, 2918, 2337,  373, 1654,  156,  451, 2728, 1491, 1271,
       2964, 2105, 1058, 2074, 2336, 1985,  363, 1539, 2071, 1370,  151,
       2899,  360, 1943, 3420, 1178, 2124, 1763,  727,  724, 1807,  257,
       2401,  642, 2352,  588, 1630,  647, 1533, 2572, 2184, 2571,  313,
       2046,  314, 1513, 2559,   59, 2548, 1848,  206, 1351, 1851,  325,
       2036, 2225,  778,  667, 1898, 2502, 2031, 2025, 1356, 1937, 1111,
          0,  476, 3370, 3369, 1335, 1081, 1936, 1522, 2847, 2012, 1934,
       1375, 2018, 1349, 1942, 1192,  250,  438, 1952,  481, 1255, 3629,
        345]])

15.539909417676284

In [201]:
rec.predicted_score_[3891, 1]

0.0

In [178]:
3891 in set(data2.test_dataset.targets)

True

In [83]:
for i in rec.similarities_[0,:]:
    if i == 1:
        print( i)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [80]:
rec.profile.dtype

dtype('float64')

In [94]:
t = data2.train_dataset.train.T

In [85]:
all(t[0,:] == t[2954,:])

False

In [95]:
t2 = t.astype(np.float64)
t2 = t2

In [96]:
sim2 = pairwise_distances(t2, metric='cosine')

In [99]:
sim2[0,[2954,  638, 2885, 1650, 1032, 1038, 1651, 1343, 1048, 1051, 3820,
        1056,  692, 2888, 3818, 2889, 1059,  690, 3143, 1657, 1658, 3472,
         684, 2166, 1339, 1660, 2161, 2160, 2159, 2157, 1662, 2156, 2155,
        3140,  677,  676, 2153,  526, 2151, 2149,  672, 2148, 2147, 3461,
        2145, 1667, 2144,  670,  669, 3453,  666, 3283, 3287, 2130,  660,
        3133, 1090, 1674, 1092, 1093, 1675, 3300,  223,  654, 1094, 2911,
        3210, 1687, 1099,  649,  648,  645, 1102, 1689, 1691, 1299, 1106,
        2940,  639, 2205, 1728, 3342, 1150, 1846, 1158, 1839, 3424, 1718,
        1719, 3416,  580, 3772,  578,  575, 3122,  572, 1723, 3386, 1294,
         282]]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [103]:
 print [k for k in np.argsort(sim2[0,:])]

[0, 1245, 584, 3045, 1250, 33, 352, 1178, 1179, 1539, 257, 2286, 2502, 1854, 585, 1180, 591, 2327, 589, 360, 293, 1120, 453, 2789, 604, 1482, 3184, 476, 315, 2849, 1192, 1595, 907, 2647, 1081, 1726, 1959, 2012, 38, 2105, 2559, 2693, 2728, 2252, 1287, 3186, 1468, 770, 1271, 2928, 363, 2918, 2847, 1568, 586, 1373, 1220, 376, 1575, 1239, 373, 588, 642, 583, 1063, 49, 2722, 1058, 108, 523, 20, 1899, 2735, 3352, 1023, 1656, 1931, 3106, 2233, 220, 1543, 1262, 31, 353, 547, 2631, 1258, 2337, 1372, 2222, 1182, 724, 3379, 2031, 436, 2011, 148, 1196, 2530, 593, 1985, 1491, 590, 1720, 1015, 1366, 3602, 1202, 1636, 3349, 1943, 3402, 496, 1356, 1533, 1132, 912, 727, 3292, 2046, 2821, 847, 582, 1268, 232, 2009, 1942, 2225, 3327, 535, 537, 3682, 2199, 2983, 2571, 2401, 2055, 1195, 46, 10, 3039, 1455, 1672, 1073, 1848, 3509, 1370, 2970, 1335, 1246, 1695, 2355, 3539, 3141, 2326, 1353, 228, 3724, 1111, 1375, 2039, 1349, 2964, 778, 1630, 1683, 1284, 2255, 3457, 2846, 2588, 2916, 1274, 1085, 1064, 3740, 1

In [126]:
a = t2[0,:]
b = t2[2954,:]

In [120]:
ab = a.dot(b)
ab


0.0

In [122]:
a.nonzero()

(array([   0,    5,    7, ..., 6031, 6034, 6039]),)

In [125]:
b.nonzero()

(array([], dtype=int64),)

In [2]:
a = data2.train_dataset.train
a.shape

(6040, 3883)

In [3]:
from sklearn.metrics.pairwise import pairwise_distances


In [4]:
pairwise_distances(a, n_jobs=4)

array([[  0.        ,  13.        ,   9.53939247, ...,   8.48528099,
         12.04159451,  19.        ],
       [ 13.        ,   0.        ,  12.48999596, ...,  11.95826054,
         15.36229134,  19.39072037],
       [  9.53939247,  12.48999596,   0.        , ...,   8.06225777,
         12.56980515,  18.76166344],
       ..., 
       [  8.48528099,  11.95826054,   8.06225777, ...,   0.        ,
         11.3578167 ,  18.41195297],
       [ 12.04159451,  15.36229134,  12.56980515, ...,  11.3578167 ,
          0.        ,  19.54482079],
       [ 19.        ,  19.39072037,  18.76166344, ...,  18.41195297,
         19.54482079,   0.        ]], dtype=float32)

In [5]:
b = _

In [7]:
b.shape

(6040, 6040)

In [9]:
b = data2.train_dataset.train.T

In [11]:
b.shape

(3883, 6040)

In [13]:
pairwise_distances(b,metric='cosine',n_jobs=4)

array([[  7.15255737e-07,   5.93337774e-01,   7.11341619e-01, ...,
          9.03107643e-01,   9.57642913e-01,   8.08767974e-01],
       [  5.93337774e-01,   0.00000000e+00,   7.34079123e-01, ...,
          9.16573822e-01,   9.69608068e-01,   8.64402175e-01],
       [  7.11341619e-01,   7.34079123e-01,   0.00000000e+00, ...,
          9.24528301e-01,   9.78004694e-01,   8.83172512e-01],
       ..., 
       [  9.03107643e-01,   9.16573822e-01,   9.24528301e-01, ...,
          2.38418579e-07,   8.02042365e-01,   7.54662156e-01],
       [  9.57642913e-01,   9.69608068e-01,   9.78004694e-01, ...,
          8.02042365e-01,   0.00000000e+00,   8.03883910e-01],
       [  8.08767974e-01,   8.64402175e-01,   8.83172512e-01, ...,
          7.54662156e-01,   8.03883910e-01,   0.00000000e+00]], dtype=float32)

In [24]:
pairwise_distances

<function sklearn.metrics.pairwise.pairwise_distances>