In [244]:
from scipy.io import mmread
import os
DATA_DIR = './ml-1m-5cv'
for cv in xrange(5):
    print(cv,':',end=' ')
    train = mmread(os.path.join(DATA_DIR,'train.%s'%cv)).A
    test = mmread(os.path.join(DATA_DIR,'test.%s'%cv)).A
    targets = np.unique(test.nonzero()[0])
    cf = IBCF(sim='cosine',knn=133,topk=5)
#     precision, recall = cf.score(train.T, test)
#     print(precision,recall)
    cf.fit(train.T)
    cf.predict(targets)
    print (cf.evaluate(test) )

0 : (0.55827814569536427, 0.062143397205823618)
1 : (0.55231788079470201, 0.059217082993249952)
2 : (0.55331125827814565, 0.061647125894519865)
3 : (0.5576158940397351, 0.058140376869835163)
4 : (0.55529801324503303, 0.060871055007001289)


In [260]:
for cv in xrange(5):
    print(cv,':',end=' ')
    train = mmread(os.path.join(DATA_DIR,'train.%s'%cv)).A
    test = mmread(os.path.join(DATA_DIR,'test.%s'%cv)).A
    targets = np.unique(test.nonzero()[0])
    cf = IBCF(sim='dot',knn=133,topk=5)
#     precision, recall = cf.score(train.T, test)
#     print(precision,recall)
    cf.fit(train.T)
    cf.predict(targets)
    print (cf.evaluate(test) )

0 : (0.47847682119205298, 0.047855389177593834)
1 : (0.48311258278145697, 0.047378851032988917)
2 : (0.4711920529801325, 0.050706741199066985)
3 : (0.49867549668874173, 0.049035804185838111)
4 : (0.47913907284768209, 0.049139787611495976)


In [261]:
for cv in xrange(5):
    print(cv,':',end=' ')
    train = mmread(os.path.join(DATA_DIR,'train.%s'%cv)).A
    test = mmread(os.path.join(DATA_DIR,'test.%s'%cv)).A
    targets = np.unique(test.nonzero()[0])
    cf = IBCF(sim='asymcos',knn=133,topk=5)
#     precision, recall = cf.score(train.T, test)
#     print(precision,recall)
    cf.fit(train.T)
    cf.predict(targets)
    print (cf.evaluate(test) )

0 : 

AttributeError: 'numpy.float64' object has no attribute 'dot'

### CF, cosine, knn =[100, 130, 150, 200, 250]

In [3]:
DATA_DIR = './ml-1m-5cv'

def foo(knn):
    perf = dict()
#     print(knn)
#     print('-'*8)

    for cv in xrange(5):
#         print(cv,':',end=' ')
        train = mmread(os.path.join(DATA_DIR,'train.%s'%cv)).A
        test = mmread(os.path.join(DATA_DIR,'test.%s'%cv)).A
        targets = np.unique(test.nonzero()[0])
        cf = IBCF(sim='cosine',knn=knn,topk=5)
    #     precision, recall = cf.score(train.T, test)
    #     print(precision,recall)
        cf.fit(train.T)
        cf.predict(targets)
        perf[cv] = cf.evaluate(test)
#         print( perf[cv])
    avg_prec = np.average([i[0] for i in perf.values()])
    avg_recall = np.average([i[1] for i in perf.values()])
    perf['avg'] = (avg_prec,avg_recall)
#     print('-'*8)
    return (knn, perf)
    
from multiprocessing import Pool
# from contextlib import closing

p = Pool(5)
p.map(foo, [100, 130, 150, 200, 250])
    

/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_j

[(100,
  {0: (0.5751655629139073, 0.064538620560558188),
   1: (0.54006622516556302, 0.056076212553703625),
   2: (0.54271523178807946, 0.060716861714399738),
   3: (0.55463576158940397, 0.058775750856392757),
   4: (0.54271523178807957, 0.059682842938793744),
   'avg': (0.55105960264900666, 0.059958057724769608)}),
 (130,
  {0: (0.56390728476821195, 0.062717423088747906),
   1: (0.55099337748344368, 0.058660052249156346),
   2: (0.55165562913907296, 0.062081687252284079),
   3: (0.55894039735099343, 0.059176523361151548),
   4: (0.55198675496688743, 0.060285973656129956),
   'avg': (0.55549668874172187, 0.06058433192149397)}),
 (150,
  {0: (0.56721854304635766, 0.063847940293046884),
   1: (0.55132450331125826, 0.056631338591857275),
   2: (0.5490066225165563, 0.061948994773005091),
   3: (0.55298013245033117, 0.057788084580691151),
   4: (0.5629139072847682, 0.061094067786868371),
   'avg': (0.55668874172185434, 0.060262085205093754)}),
 (200,
  {0: (0.57715231788079469, 0.0652557073

In [4]:
p.map(foo, [300, 350, 400, 450, 500])


[(300,
  {0: (0.58013245033112582, 0.06543247167401639),
   1: (0.55629139072847678, 0.059743034457105382),
   2: (0.55993377483443696, 0.063160969480250823),
   3: (0.57218543046357617, 0.061639462870468675),
   4: (0.55993377483443707, 0.060876316434006539),
   'avg': (0.5656953642384106, 0.062170450983169555)}),
 (350,
  {0: (0.58178807947019862, 0.06573272328161639),
   1: (0.56688741721854297, 0.061293292953501055),
   2: (0.56622516556291391, 0.064668001075818868),
   3: (0.57582781456953647, 0.061641933469565743),
   4: (0.55860927152317874, 0.061143785277662031),
   'avg': (0.5698675496688741, 0.062895947211632816)}),
 (400,
  {0: (0.57483443708609283, 0.064205080264627387),
   1: (0.56986754966887421, 0.061147738032347999),
   2: (0.56258278145695362, 0.063992899427135264),
   3: (0.57649006622516563, 0.061708349120898447),
   4: (0.56920529801324504, 0.063026624773486056),
   'avg': (0.57059602649006624, 0.062816138323699033)}),
 (450,
  {0: (0.58178807947019862, 0.0638621185

In [5]:
p.map(foo, [600,700, 800,900,1000])

[(600,
  {0: (0.57980132450331134, 0.063192330453223505),
   1: (0.57748344370860927, 0.062518332822621106),
   2: (0.55695364238410594, 0.062827927931811217),
   3: (0.58079470198675487, 0.062820534722656779),
   4: (0.56026490066225176, 0.061377979891872228),
   'avg': (0.57105960264900657, 0.06254742116443697)}),
 (700,
  {0: (0.57913907284768218, 0.063193032460317738),
   1: (0.56721854304635766, 0.060463495699422866),
   2: (0.56059602649006623, 0.063716906011984556),
   3: (0.5804635761589404, 0.062008001016471533),
   4: (0.56357615894039736, 0.062290767658730636),
   'avg': (0.57019867549668868, 0.06233444056938546)}),
 (800,
  {0: (0.58278145695364236, 0.064514599256110042),
   1: (0.56920529801324493, 0.060762612359011418),
   2: (0.55264900662251659, 0.062086609347441105),
   3: (0.56688741721854297, 0.060357594576750766),
   4: (0.56390728476821195, 0.062579558659702841),
   'avg': (0.56708609271523169, 0.062060194839803226)}),
 (900,
  {0: (0.58543046357615902, 0.065621057

# conclusion
> (450,
  {0: (0.58178807947019862, 0.063862118513803023),
   1: (0.56688741721854308, 0.060493160726376706),
   2: (0.56556291390728486, 0.064738081478524667),
   3: (0.58211920529801331, 0.062839468946100943),
   4: (0.56854304635761588, 0.063494382797993992),
   'avg': (0.57298013245033119, 0.063085442492559873)}),
   
 
> (500,
  {0: (0.57814569536423843, 0.063733701871641998),
   1: (0.57019867549668868, 0.060996964950982641),
   2: (0.5629139072847682, 0.06326488224593492),
   3: (0.57913907284768218, 0.063232834622224787),
   4: (0.57052980132450337, 0.062882255913525989),
   'avg': (0.57218543046357617, 0.062822127920862073)})]
   
   ** best is knn = 450,    'avg': (0.57298013245033119, 0.063085442492559873)})**

In [74]:
targets.shape

(604,)

In [110]:
cf.topk

5

In [238]:
cf = IBCF(sim='cosine',knn=133,topk=5)

cf.fit(train.T)

<__main__.IBCF instance at 0x7f98e8e0a830>

In [239]:
cf.predict(targets)

<__main__.IBCF instance at 0x7f98e8e0a830>

In [242]:
cf.evaluate(test)

(0.55827814569536427, 0.062143397205823618)

In [211]:
cf.user_perf

{17: (0.0, 0.0),
 23: (0.0, 0.0),
 52: (0.0, 0.0),
 59: (0.0, 0.0),
 88: (0.0, 0.0),
 89: (0.0, 0.0),
 102: (0.0, 0.0),
 103: (0.0, 0.0),
 118: (0.0, 0.0),
 119: (0.0, 0.0),
 122: (0.0, 0.0),
 123: (0.0, 0.0),
 130: (0.0, 0.0),
 140: (0.0, 0.0),
 141: (0.0, 0.0),
 152: (0.0, 0.0),
 153: (0.0, 0.0),
 165: (0.0, 0.0),
 167: (0.0, 0.0),
 176: (0.0, 0.0),
 181: (0.0, 0.0),
 184: (0.0, 0.0),
 197: (0.0, 0.0),
 198: (0.0, 0.0),
 205: (0.0, 0.0),
 215: (0.0, 0.0),
 220: (0.0, 0.0),
 222: (0.0, 0.0),
 232: (0.0, 0.0),
 235: (0.0, 0.0),
 239: (0.0, 0.0),
 248: (0.0, 0.0),
 296: (0.0, 0.0),
 304: (0.0, 0.0),
 329: (0.0, 0.0),
 333: (0.0, 0.0),
 335: (0.0, 0.0),
 344: (0.0, 0.0),
 349: (0.0, 0.0),
 391: (0.0, 0.0),
 399: (0.0, 0.0),
 406: (0.0, 0.0),
 417: (0.0, 0.0),
 418: (0.0, 0.0),
 426: (0.0, 0.0),
 428: (0.0, 0.0),
 438: (0.0, 0.0),
 440: (0.0, 0.0),
 441: (0.0, 0.0),
 451: (0.0, 0.0),
 463: (0.0, 0.0),
 477: (0.0, 0.0),
 499: (0.0, 0.0),
 537: (0.0, 0.0),
 555: (0.0, 0.0),
 558: (0.0, 0.0)

In [212]:
cf.prediction_

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [215]:
for u in [1305]:
    # print(u)
    y_true = test[u].nonzero()[0]
    y_pred = cf.recommendation_[u]
    right_rec = len(set(y_true).intersection(set(y_pred))) * 1.0
    precision = right_rec / cf.topk
    recall = right_rec / len(y_true)
    cf.user_perf[u] = (precision, recall)
cf.precision_ = np.average([i[0] for i in cf.user_perf.values()])
cf.recall_ = np.average([i[1] for i in cf.user_perf.values()])

In [139]:
cf.precision_

0.00016556291390728477

In [216]:
u

1305

In [218]:
y_true 

array([  10,   13,   20,   44,   67,  144,  159,  174,  187,  216,  218,
        246,  287,  291,  307,  319,  329,  332,  367,  369,  396,  414,
        420,  466,  471,  498,  506,  513,  575,  579,  593,  595,  634,
        641,  678,  810,  821,  847,  858,  859,  861,  907,  935,  958,
        971,  986,  989, 1005, 1025, 1050, 1052, 1065, 1106, 1109, 1110,
       1114, 1116, 1120, 1123, 1124, 1130, 1132, 1139, 1142, 1156, 1160,
       1162, 1174, 1175, 1178, 1180, 1190, 1192, 1199, 1209, 1254, 1273,
       1275, 1278, 1292, 1295, 1303, 1367, 1394, 1428, 1435, 1438, 1458,
       1478, 1485, 1502, 1516, 1541, 1551, 1553, 1570, 1575, 1581, 1593,
       1605, 1628, 1653, 1656, 1682, 1683, 1696, 1703, 1736, 1774, 1820,
       1883, 1884, 1919, 1924, 1934, 1953, 1959, 1979, 1986, 1993, 2007,
       2012, 2058, 2078, 2096, 2097, 2102, 2126, 2129, 2136, 2143, 2163,
       2198, 2301, 2307, 2409, 2411, 2419, 2420, 2478, 2488, 2489, 2494,
       2495, 2496, 2505, 2517, 2518, 2556, 2559, 25

In [219]:
y_pred

array([3480,  658, 1654, 3071, 3054])

In [220]:
set(y_true).intersection(set(y_pred))

{3480}

In [60]:
ids = cf.item_neighbors_[3].nonzero()
cf.item_neighbors_[3][ids]
ids

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132]),)

In [62]:
len(set(cf.item_neighbors_[0]).intersection(set(cf.item_neighbors_[1])))


67

In [221]:
cf.similarities_

array([[ 0.        ,  0.18155935,  0.21759824, ...,  0.26967472,
         0.28715923,  0.24448503],
       [ 0.18155935,  0.        ,  0.22451863, ...,  0.27241025,
         0.29083729,  0.25968453],
       [ 0.21759824,  0.22451863,  0.        , ...,  0.27621001,
         0.29328433,  0.26324799],
       ..., 
       [ 0.26967472,  0.27241025,  0.27621001, ...,  0.        ,
         0.240221  ,  0.2258471 ],
       [ 0.28715923,  0.29083729,  0.29328433, ...,  0.240221  ,
         0.        ,  0.23843352],
       [ 0.24448503,  0.25968453,  0.26324799, ...,  0.2258471 ,
         0.23843352,  0.        ]])

new cf

In [2]:
import dataset
from cf2 import IBCF

In [3]:
data = dataset.load_data(0)
cf_model = IBCF(knn=350,sim='cosine',topk=5)

In [18]:
cf_model.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)

<cf2.IBCF instance at 0x7fc924848830>

In [21]:
cf_model.predict(targets=data.test_dataset.targets)

<cf2.IBCF instance at 0x7fc924848830>

In [22]:
cf_model.evaluate(test=data.test_dataset.test)

(0.58178807947019862, 0.06573272328161639)

In [8]:
data.test_dataset.targets

array([  16,   18,   34,   44,   50,   52,   61,   75,   76,   98,  106,
        113,  118,  119,  124,  126,  164,  170,  175,  183,  195,  204,
        236,  242,  252,  253,  263,  275,  288,  301,  306,  319,  336,
        345,  356,  361,  372,  388,  406,  409,  430,  455,  487,  489,
        505,  520,  534,  540,  573,  583,  585,  595,  613,  615,  635,
        638,  652,  655,  668,  673,  674,  679,  682,  685,  692,  713,
        718,  728,  773,  780,  782,  785,  793,  801,  803,  808,  812,
        816,  822,  840,  860,  881,  884,  901,  905,  921,  933,  953,
        955,  965,  967,  984, 1006, 1012, 1020, 1038, 1043, 1051, 1053,
       1062, 1067, 1069, 1083, 1094, 1096, 1101, 1126, 1139, 1153, 1165,
       1172, 1184, 1199, 1204, 1205, 1231, 1243, 1246, 1252, 1261, 1268,
       1273, 1299, 1307, 1330, 1335, 1342, 1362, 1370, 1375, 1379, 1386,
       1396, 1398, 1399, 1403, 1414, 1415, 1425, 1443, 1454, 1465, 1493,
       1505, 1509, 1517, 1521, 1522, 1523, 1540, 15

In [26]:
def test(knn):
    cf_model2 = IBCF(knn=knn,sim='cosine',topk=5)
    cf_model2.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)
    cf_model2.predict(targets=data.test_dataset.targets)
    print(knn, cf_model2.evaluate(test=data.test_dataset.test))

In [27]:
from multiprocessing import  Pool
p  = Pool(5)
p.map(test,[250,300,350,400,450])

/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_j

(250, (0.57152317880794712, 0.064308069651021552))
(300, (0.58013245033112582, 0.06543247167401639))
(350, (0.58178807947019862, 0.06573272328161639))
(400, (0.57483443708609283, 0.064205080264627387))
(450, (0.58178807947019862, 0.063862118513803023))


[None, None, None, None, None]

(500, (0.57814569536423843, 0.063733701871641998))
(550, (0.57947019867549665, 0.063727672177542299))
(600, (0.57980132450331134, 0.063192330453223505))
(500, (0.57814569536423843, 0.063733701871641998))
(550, (0.57947019867549665, 0.063727672177542299))
(600, (0.57980132450331134, 0.063192330453223505))
(650, (0.57781456953642385, 0.062941489290338645))
(700, (0.57913907284768218, 0.063193032460317738))
(800, (0.58278145695364236, 0.064514599256110042))
(900, (0.58543046357615902, 0.065621057775368419))
(1000, (0.57615894039735094, 0.06479397172511564))
(2000, (0.56192052980132445, 0.062072452441247671))
(3000, (0.55397350993377492, 0.060989639401729995))
(4000, (0.55496688741721867, 0.061151428801929988))
(5, (0.45860927152317882, 0.051940949961780232))
(20, (0.52947019867549672, 0.060148277025386797))
(10, (0.49933774834437089, 0.054367846769667071))
(15, (0.51688741721854303, 0.058028704665976906))
(1, (0.42781456953642383, 0.04627476461915582))
(1, (0.42781456953642383, 0.04627476

Process PoolWorker-51:
Process PoolWorker-54:
Traceback (most recent call last):
Process PoolWorker-52:
Process PoolWorker-55:
Traceback (most recent call last):
Process PoolWorker-53:
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
    self.run()
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/home/lanxiang/miniconda2/li

In [29]:
p.map(test,[500,550,600,650,700])

[None, None, None, None, None]

In [30]:
p.map(test,[800,900,1000])

[None, None, None]

In [31]:
p.map(test,[2000, 3000, 4000])

[None, None, None]

In [32]:
p.map(test,[5,10, 15, 20])

[None, None, None, None]

In [62]:
p.map(test,[1,2,3,4,5])

[None, None, None, None, None]

In [63]:
del IBCF
from cf2 import IBCF
cf_model2 = IBCF(knn=1,sim='cosine',topk=5)
cf_model2.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)
cf_model2.predict(targets=data.test_dataset.targets)


<cf2.IBCF instance at 0x7fc920525710>

In [64]:
cf_model2.evaluate(test=data.test_dataset.test)

(0.42781456953642383, 0.04627476461915582)

In [43]:
cf_model2.item_neighbors_

{0: array([1173]),
 1: array([3256]),
 2: array([3218]),
 3: array([1488]),
 4: array([2745]),
 5: array([2086]),
 6: array([525]),
 7: array([950]),
 8: array([530]),
 9: array([1575]),
 10: array([426]),
 11: array([2135]),
 12: array([968]),
 13: array([1044]),
 14: array([519]),
 15: array([46]),
 16: array([786]),
 17: array([3444]),
 18: array([334]),
 19: array([306]),
 20: array([1449]),
 21: array([1487]),
 22: array([1396]),
 23: array([2494]),
 24: array([287]),
 25: array([1309]),
 26: array([91]),
 27: array([786]),
 28: array([1109]),
 29: array([316]),
 30: array([962]),
 31: array([2374]),
 32: array([707]),
 33: array([0]),
 34: array([2831]),
 35: array([1563]),
 36: array([3006]),
 37: array([1562]),
 38: array([1173]),
 39: array([717]),
 40: array([1134]),
 41: array([541]),
 42: array([2143]),
 43: array([1544]),
 44: array([3031]),
 45: array([215]),
 46: array([49]),
 47: array([740]),
 48: array([2473]),
 49: array([593]),
 50: array([338]),
 51: array([3069]),

In [44]:
cf_model2.recommendation_

{16: array([1478,  593, 1124, 1276, 1275]),
 18: array([1822, 1199,  957, 1276, 1106]),
 34: array([ 593, 1199,  708,  253,  575]),
 44: array([1831, 2592,  466, 2651, 2426]),
 50: array([1052, 2785, 2400, 2203, 2773]),
 52: array([2211, 1553, 1124,  802, 1120]),
 61: array([1275, 1449, 1273, 1106,  802]),
 75: array([1017,  287,  309, 2785,  708]),
 76: array([2748, 3550, 3383, 2202, 2480]),
 98: array([ 367, 1485,  581, 1478, 1993]),
 106: array([3238, 1106, 3460, 1131,  513]),
 113: array([2651, 1178,  957,  581, 1120]),
 118: array([  33, 1909,  574,  581, 2501]),
 119: array([ 367, 2785,   49, 1106, 1478]),
 124: array([1934, 1108, 1110,  575, 1277]),
 126: array([1066, 1277,  319,  802,  575]),
 164: array([1199, 1124, 2708, 1277, 2374]),
 170: array([1263, 1065, 1091, 1167, 2587]),
 175: array([2775, 1107, 1025, 1120,  253]),
 183: array([1272, 1915,  593, 1274,  802]),
 195: array([ 309,  971,  287,  802, 1124]),
 204: array([ 842,  309, 1199, 1131, 1120]),
 236: array([1025,  

In [56]:
cf_model2.prediction_ [:,615].nonzero()

(array([  20,  417,  704,  858, 1025, 1107, 1109, 1115, 1116, 1120, 1167,
        1168, 1178, 1288, 1500, 2083, 2096, 2203, 2374, 2426, 2523, 2605,
        2708, 2785, 2788, 2944, 2956, 2958, 2973, 2976, 3102, 3177, 3224,
        3277, 3282, 3302, 3303, 3321, 3328, 3329, 3342, 3353, 3383, 3384,
        3508, 3550]),)

In [61]:
del IBCF
from cf2 import IBCF


(0.41523178807947014, 0.043016722035164767)

(0.42781456953642383, 0.04627476461915582)

In [58]:
cf_model2.train[:,615].nonzero()[0]

array([ 253,  366,  466,  527,  575,  639,  713,  847,  970, 1106, 1124,
       1156, 1157, 1158, 1182, 1356, 1420, 1449, 1536, 2099, 2586, 2587,
       2651, 3126, 3248, 3301, 3341, 3510, 3512])

In [6]:
from __future__ import  print_function

import numpy as np
from scipy.spatial import distance

from scipy.io import mmread
from scipy.sparse import  csr_matrix
from sklearn.metrics.pairwise import pairwise_distances
import os
from multiprocessing import  Pool

In [10]:
import dataset
data = dataset.load_data(0)

In [30]:
class IBCF():
    def __init__(self, sim, knn, topk):
        self.sim = sim
        self.knn = knn
        self.topk = topk

    def asymcos(self, u, v, alpha=0.2):
        result = u.dot(v).astype(np.float32)
        result = result / ((np.power(u.dot(u), alpha)).dot(np.power((v.dot(v), 1 - alpha))))
        return result

    def psim(self, X, metric='cosine'):
        sim = np.zeros((X.shape[0], X.shape[0]))
        if metric == 'dot':
            sim = X.dot(X.T)
        elif metric == 'asymcos':
            for i in xrange(X.shape[0]):
                for j in xrange(X.shape[0]):
                    u = X[i, :]
                    v = X[j, :]
                    sim[i, j] = self.asymcos(u, v, alpha=0.2)
        else:
            sim = 1 - pairwise_distances(X, metric=self.sim, n_jobs=10)
        return sim

    def fit(self, train, X):
        '''


        :param train: ratings, item*user
        :param X: representations, item*dim
        :return: self
        '''
        self.train = train
        self.X = X
        self.similarities_ = self.psim(X, metric=self.sim)
        #         self.similarities_ = pairwise_distances(X,metric=self.sim,n_jobs=10) * 0.3
        self.item_neighbors_ = dict()
        #         item_num = X.shape[1]
        self.item_num = X.shape[0]
        for i in xrange(self.item_num):
            #             self.item_neighbors_[i] = np.argpartition(self.similarities_[i, :], -1 * self.knn)
            self.similarities_[i, i] = 0
            #             import pdb; pdb.set_trace()
            self.num_neighbor = self.knn if self.knn < self.similarities_.shape[0] else self.similarities_.shape[0]
            self.item_neighbors_[i] = np.argpartition(self.similarities_[i, :], self.item_num - self.num_neighbor)[-self.num_neighbor:]

        # import pdb; pdb.set_trace()
        return self

    def predict(self, targets):
        self.prediction_ = np.zeros_like(self.train)
        self.recommendation_ = dict()
        self.targets = targets
        for user in targets:
            # self.purchased_items = self.X[:, user].nonzero()[0]
            #             purchased_items = self.X[:, user].nonzero()[0]
            for i in xrange(self.item_num):
                neighbors = self.item_neighbors_[i]
                self.prediction_[i, user] = self.train[neighbors, user].dot(self.similarities_[i,neighbors])
            purchased_items = self.train[:, user].nonzero()[0]
            self.prediction_[purchased_items, user] = 0

#             s = self.prediction_[:, user].shape
            #             self.prediction_[:,user] = np.random.random(size=s)
            tmp_k = self.topk if self.topk < self.num_neighbor else self.num_neighbor
            self.recommendation_[user] = np.argpartition(self.prediction_[:, user], self.item_num - tmp_k)[
                                         -1 * tmp_k:]
#         import pdb; pdb.set_trace()

        #             print(user, self.recommendation_[user])
        return self

    def evaluate(self, test):
        '''


        :param test: user*item
        :return:
        '''
        self.user_perf = dict()
        for u in self.targets:
            y_true = test[u].nonzero()[0]
            y_pred = self.recommendation_[u]
            right_rec = len(set(y_true).intersection(set(y_pred))) * 1.0
            precision = right_rec / self.topk
            recall = right_rec / len(y_true)
            self.user_perf[u] = (precision, recall)
        self.precision_ = np.average([i[0] for i in self.user_perf.values()])
        self.recall_ = np.average([i[1] for i in self.user_perf.values()])
        return self.precision_, self.recall_


In [29]:
    cf_model2 = IBCF(knn=2,sim='cosine',topk=5)
    cf_model2.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)
    cf_model2.predict(targets=data.test_dataset.targets)
    
    perf[knn] = (knn, cf_model2.evaluate(test=data.test_dataset.test))
    print (perf)

    

> <ipython-input-26-e642d592f291>(72)predict()
-> return self
(Pdb) self.recommendation_
{2052: array([3675, 3672]), 4105: array([   0, 2710]), 2060: array([2203, 2785]), 4110: array([1180, 3383]), 16: array([ 593, 1124]), 4113: array([1108, 1110]), 18: array([2511,  574]), 4115: array([ 971, 1106]), 4119: array([1295, 1215]), 2077: array([  10, 1504]), 34: array([1107,  253]), 2084: array([1943, 1435]), 4502: array([1774, 1173]), 4135: array([1168,  869]), 2089: array([1148, 1258]), 44: array([ 357, 1964]), 4141: array([  18, 1428]), 2095: array([2203, 1110]), 50: array([3509, 2162]), 52: array([1124, 1120]), 2104: array([2200,  575]), 2107: array([2191, 2162]), 61: array([1275, 1106]), 4159: array([2773, 1124]), 4160: array([1406, 2200]), 2114: array([1773,   33]), 75: array([2557,  309]), 76: array([2785, 2480]), 2128: array([1789, 1792]), 2145: array([1029, 3462]), 98: array([2203,  581]), 106: array([1131,  513]), 113: array([1178, 1120]), 118: array([2399, 2162]), 119: array([156

(Pdb) self.recommendation_[user]
array([1108, 1110])
(Pdb) item
*** NameError: name 'item' is not defined
(Pdb) i
3705
(Pdb) targets
array([  16,   18,   34,   44,   50,   52,   61,   75,   76,   98,  106,
        113,  118,  119,  124,  126,  164,  170,  175,  183,  195,  204,
        236,  242,  252,  253,  263,  275,  288,  301,  306,  319,  336,
        345,  356,  361,  372,  388,  406,  409,  430,  455,  487,  489,
        505,  520,  534,  540,  573,  583,  585,  595,  613,  615,  635,
        638,  652,  655,  668,  673,  674,  679,  682,  685,  692,  713,
        718,  728,  773,  780,  782,  785,  793,  801,  803,  808,  812,
        816,  822,  840,  860,  881,  884,  901,  905,  921,  933,  953,
        955,  965,  967,  984, 1006, 1012, 1020, 1038, 1043, 1051, 1053,
       1062, 1067, 1069, 1083, 1094, 1096, 1101, 1126, 1139, 1153, 1165,
       1172, 1184, 1199, 1204, 1205, 1231, 1243, 1246, 1252, 1261, 1268,
       1273, 1299, 1307, 1330, 1335, 1342, 1362, 1370, 1375, 137

NameError: name 'knn' is not defined

         def predict(self, targets):
                self.prediction_ = np.zeros_like(self.train)
                self.recommendation_ = dict()
                self.targets = targets
                for user in targets:
                    # self.purchased_items = self.X[:, user].nonzero()[0]
                    #             purchased_items = self.X[:, user].nonzero()[0]
                    for i in xrange(self.item_num):
                        neighbors = self.item_neighbors_[i]
                        self.prediction_[i, user] = self.train[neighbors, user].dot(self.similarities_[i,neighbors])
                    purchased_items = self.train[:, user].nonzero()[0]
                    self.prediction_[purchased_items, user] = 0
        #             stub
                    self.prediction_[:, user] = 0

        #             s = self.prediction_[:, user].shape
                    #             self.prediction_[:,user] = np.random.random(size=s)
                tmp_k = self.topk if self.topk < self.num_neighbor else self.num_neighbor
                self.recommendation_[user] = np.argpartition(self.prediction_[:, user], self.item_num - self.topk)[
                                             -1 * self.topk:]
            import pdb; pdb.set_trace()

            #             print(user, self.recommendation_[user])
            return self def predict(self, targets):
            self.prediction_ = np.zeros_like(self.train)
            self.recommendation_ = dict()
            self.targets = targets
            for user in targets:
                # self.purchased_items = self.X[:, user].nonzero()[0]
                #             purchased_items = self.X[:, user].nonzero()[0]
                for i in xrange(self.item_num):
                    neighbors = self.item_neighbors_[i]
                    self.prediction_[i, user] = self.train[neighbors, user].dot(self.similarities_[i,neighbors])
                purchased_items = self.train[:, user].nonzero()[0]
                self.prediction_[purchased_items, user] = 0
    #             stub
                self.prediction_[:, user] = 0

    #             s = self.prediction_[:, user].shape
                #             self.prediction_[:,user] = np.random.random(size=s)
                tmp_k = self.topk if self.topk < self.num_neighbor else self.num_neighbor
                self.recommendation_[user] = np.argpartition(self.prediction_[:, user], self.item_num - self.topk)[
                                             -1 * self.topk:]
            import pdb; pdb.set_trace()

            #             print(user, self.recommendation_[user])
            return self

In [27]:
perf = dict()
def test_neighbors(knn):
    cf_model2 = IBCF(knn=knn,sim='cosine',topk=5)
    cf_model2.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)
    cf_model2.predict(targets=data.test_dataset.targets)
    
    perf[knn] = (knn, cf_model2.evaluate(test=data.test_dataset.test))
    print (perf)
#     return

In [15]:
pp =  Pool(10) 
pp.map(test_neighbors,[1,2,3,4,5,6,7,8,9,10])

/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_j

{1: (1, (0.09602649006622517, 0.010572003382280011))}
{8: (8, (0.48576158940397346, 0.052608912386610057))}
{6: (6, (0.47384105960264911, 0.052105718157899633))}
{4: (4, (0.3688741721854305, 0.041122600131997117))}
{10: (10, (0.49933774834437089, 0.054367846769667071))}
{2: (2, (0.18774834437086091, 0.019880892417508515))}
{7: (7, (0.47251655629139067, 0.051778644415428093))}
{3: (3, (0.27682119205298017, 0.031035966045551686))}
{5: (5, (0.45860927152317882, 0.051940949961780232))}
{9: (9, (0.49238410596026488, 0.053800012991470275))}


[None, None, None, None, None, None, None, None, None, None]

Process PoolWorker-32:
Process PoolWorker-35:
Process PoolWorker-31:
Process PoolWorker-40:
Process PoolWorker-33:
Process PoolWorker-36:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-38:
Process PoolWorker-39:
Traceback (most recent call last):
Process PoolWorker-37:
Process PoolWorker-34:
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
Traceback (most recent ca

In [25]:
pp =  Pool(10) 
pp.map(test_neighbors,[11,12,13, 14, 15, 16, 17, 18, 19,20])

/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_j

{16: (16, (0.51788079470198667, 0.058121333973766245))}
{15: (15, (0.51688741721854303, 0.058028704665976906))}
{13: (13, (0.5158940397350994, 0.058524916060488319))}
{14: (14, (0.51556291390728481, 0.058420968011200253))}
{19: (19, (0.52781456953642381, 0.059851135056433552))}
{12: (12, (0.50662251655629142, 0.056577202119597977))}
{20: (20, (0.52947019867549672, 0.060148277025386797))}
{11: (11, (0.50562913907284768, 0.056094263707831209))}
{18: (18, (0.52119205298013249, 0.058758725850682703))}
{17: (17, (0.5155629139072847, 0.05834398050279458))}


[None, None, None, None, None, None, None, None, None, None]

{16: (16, (0.51788079470198667, 0.058121333973766245)), 100: (100, (0.5751655629139073, 0.064538620560558188))}
{150: (150, (0.56721854304635766, 0.063847940293046884)), 15: (15, (0.51688741721854303, 0.058028704665976906))}
{200: (200, (0.57715231788079469, 0.065255707323329734)), 13: (13, (0.5158940397350994, 0.058524916060488319))}
{250: (250, (0.57152317880794712, 0.064308069651021552)), 14: (14, (0.51556291390728481, 0.058420968011200253))}
{19: (19, (0.52781456953642381, 0.059851135056433552)), 300: (300, (0.58013245033112582, 0.06543247167401639))}
{12: (12, (0.50662251655629142, 0.056577202119597977)), 350: (350, (0.58178807947019862, 0.06573272328161639))}
{400: (400, (0.57483443708609283, 0.064205080264627387)), 20: (20, (0.52947019867549672, 0.060148277025386797))}


Process PoolWorker-43:
Process PoolWorker-48:
Traceback (most recent call last):
Process PoolWorker-47:
Process PoolWorker-49:
Process PoolWorker-46:
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-42:
Traceback (most recent call last):
Process PoolWorker-50:
Process PoolWorker-45:
Traceback (most recent call last):
Process PoolWorker-44:
Traceback (most recent call last):
Process PoolWorker-41:
Traceback (most recent call last):
Traceback (most recent call last):
    self.run()
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/li

In [33]:
pp =  Pool(10) 
pp.map(test_neighbors,[100,150,200,250,300,350,400,450,500,550,600])

/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)
/home/lanxiang/miniconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_j

{100: (100, (0.5751655629139073, 0.064538620560558188))}
{200: (200, (0.57715231788079469, 0.065255707323329734))}
{150: (150, (0.56721854304635766, 0.063847940293046884))}
{250: (250, (0.57152317880794712, 0.064308069651021552))}
{300: (300, (0.58013245033112582, 0.06543247167401639))}
{350: (350, (0.58178807947019862, 0.06573272328161639))}
{400: (400, (0.57483443708609283, 0.064205080264627387))}
{450: (450, (0.58178807947019862, 0.063862118513803023))}
{500: (500, (0.57814569536423843, 0.063733701871641998))}
{550: (550, (0.57947019867549665, 0.063727672177542299))}
{600: (600, (0.57980132450331134, 0.063192330453223505)), 100: (100, (0.5751655629139073, 0.064538620560558188))}


[None, None, None, None, None, None, None, None, None, None, None]

Process PoolWorker-75:
Process PoolWorker-72:
Process PoolWorker-73:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-80:
Process PoolWorker-74:
Process PoolWorker-79:
Traceback (most recent call last):
Process PoolWorker-71:
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-76:
Process PoolWorker-78:
Process PoolWorker-77:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
    self.run()
    self.run()
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, 

In [53]:
import cf3

knn = 130
cf_model3 = cf3.IBCF(knn=knn, sim='cosine', topk=5, s = 4)
cf_model3.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)
cf_model3.predict(targets=data.test_dataset.targets)

print(knn, cf_model3.evaluate(test=data.test_dataset.test))
# print (perf)

130 (0.56390728476821195, 0.062717423088747906)


In [54]:
import cf2
knn = 130
cf_model2 = cf2.IBCF(knn=knn, sim='cosine', topk=5)
cf_model2.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)
cf_model2.predict(targets=data.test_dataset.targets)

print(knn, cf_model3.evaluate(test=data.test_dataset.test))
# print (perf)

130 (0.56390728476821195, 0.062717423088747906)


In [55]:
cf_model2.similarities_ 

array([[ 0.        ,  0.39991647,  0.27403855, ...,  0.09707808,
         0.04339206,  0.19070071],
       [ 0.39991647,  0.        ,  0.25574201, ...,  0.08617109,
         0.03109431,  0.13361746],
       [ 0.27403855,  0.25574201,  0.        , ...,  0.0782727 ,
         0.02259541,  0.11769235],
       ..., 
       [ 0.09707808,  0.08617109,  0.0782727 , ...,  0.        ,
         0.19985199,  0.23855489],
       [ 0.04339206,  0.03109431,  0.02259541, ...,  0.19985199,
         0.        ,  0.19198692],
       [ 0.19070071,  0.13361746,  0.11769235, ...,  0.23855489,
         0.19198692,  0.        ]], dtype=float32)

In [56]:
cf_model3.similarities_

array([[ 0.        ,  0.39991647,  0.27403855, ...,  0.09707808,
         0.04339206,  0.19070071],
       [ 0.39991647,  0.        ,  0.25574201, ...,  0.08617109,
         0.03109431,  0.13361746],
       [ 0.27403855,  0.25574201,  0.        , ...,  0.0782727 ,
         0.        ,  0.11769235],
       ..., 
       [ 0.09707808,  0.08617109,  0.0782727 , ...,  0.        ,
         0.19985199,  0.23855489],
       [ 0.04339206,  0.03109431,  0.        , ...,  0.19985199,
         0.        ,  0.19198692],
       [ 0.19070071,  0.13361746,  0.11769235, ...,  0.23855489,
         0.19198692,  0.        ]])

In [60]:
(sum(cf_model2.similarities_ != cf_model3.similarities_))

array([ 310,  414,  547, ..., 1349, 1933,  613])

In [72]:
reload(cf3)    


<module 'cf3' from 'cf3.pyc'>

In [160]:
# import cf3
reload(cf3)    
knn = 500
cf_model3 = cf3.IBCF(knn=knn, sim='asymcos', topk=5, s = 100)
cf_model3.fit(train=data.train_dataset.train.T, X = data.train_dataset.train.T)
cf_model3.predict(targets=data.test_dataset.targets)

print(knn, cf_model3.evaluate(test=data.test_dataset.test))


500 (0.030132450331125833, 0.0018186373247710997)


In [158]:
cf_model3.similarities_.shape

(3706, 3706)

In [150]:
 cf_model3.predict(targets=data.test_dataset.targets)


<cf3.IBCF instance at 0x7f2405734d40>

In [151]:
 print(knn, cf_model3.evaluate(test=data.test_dataset.test))


130 (0.030132450331125833, 0.0018186373247710997)


In [122]:
np.power(2,1-0.7)

1.2311444133449163

In [88]:
cf_model3.u

array([ 0.,  0.,  0., ...,  0.,  0.,  0.], dtype=float32)

In [90]:
cf_model3.v

array([ 0.,  0.,  0., ...,  0.,  0.,  0.], dtype=float32)

In [92]:
cf_model3.asymcos(cf_model3.u,cf_model3.v)

88

In [111]:
max(1e-10,1e-11)

1e-10

In [94]:
 def asymcos(self, u, v, alpha=0.2):
        # print(u)
        # print(v)
        self.u = u
        self.v = v
        print('asdf')
        # import pdb; pdb.set_trace()
        result = np.dot(u,v.T)
        result = result / ((np.power(np.dot(u,u.T), alpha)).dot(np.power((np.dot(v,v.T), 1 - alpha))))
        return result

In [96]:
cf_model3.asymcos = asymcos

In [97]:
cf_model3.asymcos(cf_model3.u,cf_model3.v)

TypeError: asymcos() takes at least 3 arguments (2 given)

In [147]:
np.power(np.dot(a, a.T), 0.5)

array([[ 1.41421356,  0.84657907],
       [ 0.84657907,  0.71374492]])

In [145]:
# a = np.random.random([2,2])
a[0] = 1
a

array([[ 1.        ,  1.        ],
       [ 0.00295733,  0.71373879]])

In [ ]:
from multiprocessing import  Pool
p = Pool(10)
p.map()


    def asymcos(self, u, v, alpha=0.2):
        import pdb; pdb.set_trace()
        result = u.dot(v).astype(np.float32)
        result = result / ((np.power(u.dot(u), alpha)).dot(np.power((v.dot(v), 1 - alpha))))
        return result

In [77]:
 def asymcos( u, v, alpha=0.2):
        print(u)
        print(v)
        self.u = u
        self.v = v

        # import pdb; pdb.set_trace()
        # result = np.dot(u,v.T)
        # result = result / ((np.power(np.dot(u,u.T), alpha)).dot(np.power((np.dot(v,v.T), 1 - alpha))))
        # return result
        return 88

In [81]:
def func(p):
    i = p[0]
    j = p[1]
    return (i,j,np.random.rand())

In [83]:
x = np.random.random((100,100))
def foo(x):
    ids = []
    for i in xrange(100):
        for j in xrange(100):
            ids.append((i,j))
    from multiprocessing import  Pool
    p = Pool(10)
    return p.map(func,ids)

In [84]:
foo(x)

[(0, 0, 0.4022239575757687),
 (0, 1, 0.42843209587313524),
 (0, 2, 0.948091744813115),
 (0, 3, 0.6705036431708098),
 (0, 4, 0.36737587164880836),
 (0, 5, 0.7766212278394362),
 (0, 6, 0.7709175548991325),
 (0, 7, 0.04466948172012997),
 (0, 8, 0.6672917875714607),
 (0, 9, 0.7919493832938349),
 (0, 10, 0.0519089958742216),
 (0, 11, 0.3555654530146364),
 (0, 12, 0.06197286829834148),
 (0, 13, 0.08545281638903768),
 (0, 14, 0.2063585623030323),
 (0, 15, 0.9623883166659596),
 (0, 16, 0.7214766539854942),
 (0, 17, 0.6925669426777152),
 (0, 18, 0.16002927418765578),
 (0, 19, 0.552084767758656),
 (0, 20, 0.33303674174206355),
 (0, 21, 0.3045824556653032),
 (0, 22, 0.22096230233254965),
 (0, 23, 0.9807186849032056),
 (0, 24, 0.7407158483735824),
 (0, 25, 0.41307305229838687),
 (0, 26, 0.3320032364588107),
 (0, 27, 0.2175042443612969),
 (0, 28, 0.3463371772020645),
 (0, 29, 0.35990808529205986),
 (0, 30, 0.5655699573015335),
 (0, 31, 0.26242847898914246),
 (0, 32, 0.7243611801830813),
 (0, 33, 0.

Process PoolWorker-273:
Process PoolWorker-276:
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-275:
Traceback (most recent call last):
Process PoolWorker-278:
Process PoolWorker-280:
Process PoolWorker-271:
Process PoolWorker-277:
Process PoolWorker-272:
Process PoolWorker-274:
Process PoolWorker-279:
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/lanxiang/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
    self.run()
    self.run()
Traceback (

In [2]:
import numpy as np
import numba

In [94]:
def foo(x, alpha=0.2):
    numerator = x.dot(x.T)
    x = x.astype(np.float32)
    dominator_a = np.power(numerator,alpha)
    dominator_b = np.power(numerator,(1-alpha))
    sim = np.zeros_like(numerator).astype(np.float64)
    for i in xrange(numerator.shape[0]):
        for j in xrange(numerator.shape[0]):
            sim[i,j] = numerator[i,j] / dominator_a[i,i] / dominator_b[j,j]
    return sim
    

In [94]:
def foo(x, alpha=0.2):
    numerator = x.dot(x.T)
    x = x.astype(np.float32)
    dominator_a = np.power(numerator,alpha)
    dominator_b = np.power(numerator,(1-alpha))
    sim = np.zeros_like(numerator).astype(np.float64)
    for i in xrange(numerator.shape[0]):
        for j in xrange(numerator.shape[0]):
            sim[i,j] = numerator[i,j] / dominator_a[i,i] / dominator_b[j,j]
    return sim
    

In [95]:
x = np.random.random((4000,6000))

In [55]:
x = (x > 0.5).astype(np.float32)

In [56]:
x

array([[ 1.,  0.,  1., ...,  1.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  1.,  1.],
       [ 1.,  1.,  0., ...,  1.,  0.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  1., ...,  1.,  0.,  0.],
       [ 1.,  1.,  1., ...,  1.,  0.,  1.]], dtype=float32)

In [65]:
x = np.array([[3,4,5],
              [37,8,9],
              [23,321,12],
              [3,2,2]])

In [36]:
import scipy.spatial.dis as ss

In [96]:
aa = 1-ss.distance.squareform( ss.distance.pdist(x, metric='cosine')) 

In [97]:
bb = foo(x,0.5)

In [101]:
aa

array([[ 1.        ,  0.74694819,  0.75217027, ...,  0.74313405,
         0.74824976,  0.74322706],
       [ 0.74694819,  1.        ,  0.75174012, ...,  0.74535303,
         0.75000695,  0.75221202],
       [ 0.75217027,  0.75174012,  1.        , ...,  0.75012411,
         0.75076773,  0.74945748],
       ..., 
       [ 0.74313405,  0.74535303,  0.75012411, ...,  1.        ,
         0.74615838,  0.74836451],
       [ 0.74824976,  0.75000695,  0.75076773, ...,  0.74615838,
         1.        ,  0.75313704],
       [ 0.74322706,  0.75221202,  0.74945748, ...,  0.74836451,
         0.75313704,  1.        ]])

In [102]:
bb

array([[ 1.        ,  0.74694819,  0.75217027, ...,  0.74313405,
         0.74824976,  0.74322706],
       [ 0.74694819,  1.        ,  0.75174012, ...,  0.74535303,
         0.75000695,  0.75221202],
       [ 0.75217027,  0.75174012,  1.        , ...,  0.75012411,
         0.75076773,  0.74945748],
       ..., 
       [ 0.74313405,  0.74535303,  0.75012411, ...,  1.        ,
         0.74615838,  0.74836451],
       [ 0.74824976,  0.75000695,  0.75076773, ...,  0.74615838,
         1.        ,  0.75313704],
       [ 0.74322706,  0.75221202,  0.74945748, ...,  0.74836451,
         0.75313704,  1.        ]])

In [90]:

numerator = x.dot(x.T)


dominator_a = np.power(numerator,0.5)
dominator_b = np.power(numerator,(1-0.5))
sim = np.zeros_like(numerator).astype(np.float64)
for i in xrange(numerator.shape[0]):
    for j in xrange(numerator.shape[0]):
        sim[i,j] = numerator[i,j] / dominator_a[i,i] / dominator_b[j,j]
#     return sim


In [79]:
numerator[0,0]

50

In [80]:
dominator_a[0,0]

7.0710678118654755

In [81]:
dominator_b[0,0]

7.0710678118654755

In [82]:
numerator.dtype

dtype('int64')

In [91]:
sim

array([[ 1.        ,  0.68329763,  0.62049526,  0.92609239],
       [ 0.68329763,  1.        ,  0.28146464,  0.90381724],
       [ 0.62049526,  0.28146464,  1.00000012,  0.55353385],
       [ 0.92609239,  0.90381724,  0.55353385,  1.        ]])

In [103]:
%timeit foo(x)

1 loop, best of 3: 10.9 s per loop


In [105]:
from numba import  jit

In [107]:
@jit
def bar(x, alpha=0.2):
    numerator = x.dot(x.T)
    x = x.astype(np.float32)
    dominator_a = np.power(numerator,alpha)
    dominator_b = np.power(numerator,(1-alpha))
    sim = np.zeros_like(numerator).astype(np.float64)
    for i in xrange(numerator.shape[0]):
        for j in xrange(numerator.shape[0]):
            sim[i,j] = numerator[i,j] / dominator_a[i,i] / dominator_b[j,j]
    return sim
    

In [108]:
%timeit foo(x)

1 loop, best of 3: 2.83 s per loop


In [4]:
import rec3 as cf3
import rec4 as cf4

In [5]:
import dataset3
data = dataset3.load_data(1)

In [8]:
def foo(knn = 100):
    cf_model3 = cf3.IBCF(sim='asymcos')
    cf_model3.fit(train_ratings=data.train_dataset.train, profile = data.train_dataset.train.T)
    cf_model3.compute_score(input_ratings = data.train_dataset.newusers, topN = 130 ,targets=data.test_dataset.targets)
    cf_model3.produce_reclist(targets=data.test_dataset.targets)

    print(knn, cf_model3.evaluate(test=data.test_dataset.test, rec_len = 5))


In [7]:
foo()
#cosine

(100, (0.55364238410596034, 0.059138972223670261))


In [10]:
foo()

(100, (0.59503311258278146, 0.065067330453778133))


In [125]:
foo()

(100, (0.55364238410596034, 0.059138972223670261))


In [124]:
%timeit foo()

(100, (0.55364238410596034, 0.059138972223670261))
(100, (0.55364238410596034, 0.059138972223670261))
(100, (0.55364238410596034, 0.059138972223670261))
(100, (0.55364238410596034, 0.059138972223670261))
1 loop, best of 3: 6.89 s per loop


In [179]:
reload(cf4)

<module 'rec4' from 'rec4.pyc'>

In [160]:
def bar(knn = 100):
    cf_model3 = cf4.IBCF(sim='asymcos')
    cf_model3.fit(train_ratings=data.train_dataset.train, profile = data.train_dataset.train.T)
    cf_model3.compute_score(input_ratings = data.train_dataset.newusers, topN = knn ,targets=data.test_dataset.targets)
    cf_model3.produce_reclist(targets=data.test_dataset.targets)

    print(knn, cf_model3.evaluate(test=data.test_dataset.test, rec_len = 5))


In [162]:
%timeit bar()

(100, (0.58311258278145706, 0.06253348143267419))
(100, (0.58311258278145706, 0.06253348143267419))
(100, (0.58311258278145706, 0.06253348143267419))
(100, (0.58311258278145706, 0.06253348143267419))
1 loop, best of 3: 17.8 s per loop


In [164]:
%timeit cf_model3.asymmetric_cosine(x)
#without jit

1 loop, best of 3: 11.1 s per loop


In [177]:
%timeit cf_model3.asymmetric_cosine(x)
#with jit

1 loop, best of 3: 10.9 s per loop


In [165]:
%timeit foo(x)

(array([[ 0.99818471,  0.35584682,  0.44809273, ...,  0.27442292,
         0.21894977,  0.8257528 ],
       [ 0.35023823,  0.18242984,  0.69295167, ...,  0.13983286,
         0.14993711,  0.56221281],
       [ 0.86312008,  0.09812175,  0.71869539, ...,  0.43413864,
         0.02658857,  0.79813103],
       ..., 
       [ 0.98825352,  0.15313408,  0.24248681, ...,  0.11605724,
         0.23304765,  0.66221607],
       [ 0.72807365,  0.26073757,  0.41487759, ...,  0.13180276,
         0.06037639,  0.21962795],
       [ 0.29737165,  0.40656076,  0.73094167, ...,  0.83582626,
         0.51496833,  0.29727897]]), (0.55364238410596034, 0.059138972223670261))
(array([[ 0.99818471,  0.35584682,  0.44809273, ...,  0.27442292,
         0.21894977,  0.8257528 ],
       [ 0.35023823,  0.18242984,  0.69295167, ...,  0.13983286,
         0.14993711,  0.56221281],
       [ 0.86312008,  0.09812175,  0.71869539, ...,  0.43413864,
         0.02658857,  0.79813103],
       ..., 
       [ 0.98825352,  0.1

In [180]:
knn = 130
cf_model3 = cf4.IBCF(sim='asymcos')
cf_model3.fit(train_ratings=data.train_dataset.train, profile = data.train_dataset.train.T)
cf_model3.compute_score(input_ratings = data.train_dataset.newusers, topN = knn ,targets=data.test_dataset.targets)
cf_model3.produce_reclist(targets=data.test_dataset.targets)

print(knn, cf_model3.evaluate(test=data.test_dataset.test, rec_len = 5))


ZeroDivisionError: division by zero

In [174]:
cf_model3

<rec4.IBCF instance at 0x7f4a9deaf5a8>

In [1]:
from pprint import  pprint

In [4]:
#hidden size 128
tmp = {10: ((0.11887417218543046, 0.0080361610000312007), {10: {('decode', 'asymcos', 5): (0.032450331125827819, 0.0011524367385721183), ('hidden', 'cosine', 500): (0.2867549668874172, 0.02674284813666138), ('decode', 'asymcos', 200): (0.067218543046357618, 0.0032705215513467545), ('hidden_sigmoid', 'cosine', 5): (0.35000000000000003, 0.035061499070888451), ('hidden', 'cosine', 200): (0.33476821192052986, 0.031096601623936321), ('decode', 'asymcos', 500): (0.073841059602649015, 0.0037131233174227431), ('hidden', 'asymcos', 500): (0.019867549668874173, 0.00049754824708098512), ('decode', 'cosine', 5): (0.40827814569536425, 0.042895577573777419), ('hidden', 'asymcos', 200): (0.0069536423841059609, 0.00021055166782992183), ('hidden_sigmoid', 'asymcos', 5): (0.024834437086092717, 0.0013675062868627602), ('decode', 'cosine', 200): (0.38079470198675502, 0.036211798393010156), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.34238410596026492, 0.030303878168686547), ('hidden_sigmoid', 'asymcos', 500): (0.21390728476821191, 0.01739901452256877), ('hidden', 'cosine', 5): (0.40430463576158943, 0.04319639284872636), ('hidden_sigmoid', 'cosine', 200): (0.37682119205298015, 0.03389033530784983), ('hidden_sigmoid', 'asymcos', 200): (0.22483443708609274, 0.017266746470483402), ('hidden_sigmoid', 'cosine', 500): (0.29801324503311261, 0.025269416351422238)}, 20: {('decode', 'asymcos', 5): (0.015894039735099341, 0.0005693260905822896), ('hidden', 'cosine', 500): (0.36953642384105961, 0.033753312203989597), ('decode', 'asymcos', 200): (0.05066225165562914, 0.0024881686460818133), ('hidden_sigmoid', 'cosine', 5): (0.37384105960264902, 0.038338938216124184), ('hidden', 'cosine', 200): (0.38708609271523181, 0.034410425909013241), ('decode', 'asymcos', 500): (0.048675496688741722, 0.0028777555474772194), ('hidden', 'asymcos', 500): (0.069536423841059597, 0.003397251117226835), ('decode', 'cosine', 5): (0.42450331125827812, 0.045376044779644867), ('hidden', 'asymcos', 200): (0.029139072847682121, 0.0010506949600094029), ('hidden_sigmoid', 'asymcos', 5): (0.091721854304635766, 0.0060136763092525584), ('decode', 'cosine', 200): (0.36357615894039741, 0.03229493197647456), ('hidden', 'asymcos', 5): (0.0013245033112582781, 2.4471455006096599e-05), ('decode', 'cosine', 500): (0.32384105960264903, 0.028640448043775663), ('hidden_sigmoid', 'asymcos', 500): (0.42019867549668877, 0.036111954303831649), ('hidden', 'cosine', 5): (0.43013245033112585, 0.045736199532101396), ('hidden_sigmoid', 'cosine', 200): (0.35430463576158938, 0.031541114917292064), ('hidden_sigmoid', 'asymcos', 200): (0.41887417218543044, 0.038106149170784913), ('hidden_sigmoid', 'cosine', 500): (0.3208609271523179, 0.02617201864435478)}, 5: {('decode', 'asymcos', 5): (0.080132450331125843, 0.0043932010190209743), ('hidden', 'cosine', 500): (0.29768211920529802, 0.029128269882594607), ('decode', 'asymcos', 200): (0.18344370860927153, 0.013021838255424007), ('hidden_sigmoid', 'cosine', 5): (0.33410596026490069, 0.033837651355020912), ('hidden', 'cosine', 200): (0.33807947019867546, 0.031881780411132508), ('decode', 'asymcos', 500): (0.18013245033112585, 0.011826206786114546), ('hidden', 'asymcos', 500): (0.0, 0.0), ('decode', 'cosine', 5): (0.38609271523178806, 0.040789804272097371), ('hidden', 'asymcos', 200): (0.00033112582781456954, 1.8986572695789538e-06), ('hidden_sigmoid', 'asymcos', 5): (0.1119205298013245, 0.0063958224521917248), ('decode', 'cosine', 200): (0.35993377483443717, 0.035611960634400877), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.31192052980132451, 0.027362187808267779), ('hidden_sigmoid', 'asymcos', 500): (0.26026490066225166, 0.020769173906903946), ('hidden', 'cosine', 5): (0.39834437086092717, 0.042899526776910821), ('hidden_sigmoid', 'cosine', 200): (0.32913907284768212, 0.028092523007686082), ('hidden_sigmoid', 'asymcos', 200): (0.32251655629139075, 0.026882492631002352), ('hidden_sigmoid', 'cosine', 500): (0.276158940397351, 0.0218121175250333)}, 15: {('decode', 'asymcos', 5): (0.018543046357615892, 0.00061348439877666758), ('hidden', 'cosine', 500): (0.31688741721854308, 0.027711483746757824), ('decode', 'asymcos', 200): (0.047350993377483448, 0.0024849597995780085), ('hidden_sigmoid', 'cosine', 5): (0.36754966887417218, 0.036666558739426494), ('hidden', 'cosine', 200): (0.34271523178807944, 0.030280766503057343), ('decode', 'asymcos', 500): (0.0543046357615894, 0.0027853259020663435), ('hidden', 'asymcos', 500): (0.032781456953642388, 0.0013735862623084831), ('decode', 'cosine', 5): (0.42218543046357621, 0.044703244877262856), ('hidden', 'asymcos', 200): (0.0099337748344370865, 0.00046694616697775897), ('hidden_sigmoid', 'asymcos', 5): (0.070860927152317871, 0.0038849465894476021), ('decode', 'cosine', 200): (0.37052980132450331, 0.032712935483188314), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.30894039735099343, 0.027097628247914288), ('hidden_sigmoid', 'asymcos', 500): (0.40066225165562913, 0.035824390388427149), ('hidden', 'cosine', 5): (0.42880794701986757, 0.045053169496441281), ('hidden_sigmoid', 'cosine', 200): (0.36754966887417218, 0.034474129038475097), ('hidden_sigmoid', 'asymcos', 200): (0.39635761589403973, 0.036034705996876706), ('hidden_sigmoid', 'cosine', 500): (0.31225165562913909, 0.026107515741613546)}}), 20: ((0.11920529801324503, 0.00769805438078727), {10: {('decode', 'asymcos', 5): (0.032450331125827819, 0.0011524367385721183), ('hidden', 'cosine', 500): (0.2867549668874172, 0.02674284813666138), ('decode', 'asymcos', 200): (0.067218543046357618, 0.0032705215513467545), ('hidden_sigmoid', 'cosine', 5): (0.35000000000000003, 0.035061499070888451), ('hidden', 'cosine', 200): (0.33476821192052986, 0.031096601623936321), ('decode', 'asymcos', 500): (0.073841059602649015, 0.0037131233174227431), ('hidden', 'asymcos', 500): (0.019867549668874173, 0.00049754824708098512), ('decode', 'cosine', 5): (0.40827814569536425, 0.042895577573777419), ('hidden', 'asymcos', 200): (0.0069536423841059609, 0.00021055166782992183), ('hidden_sigmoid', 'asymcos', 5): (0.024834437086092717, 0.0013675062868627602), ('decode', 'cosine', 200): (0.38079470198675502, 0.036211798393010156), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.34238410596026492, 0.030303878168686547), ('hidden_sigmoid', 'asymcos', 500): (0.21390728476821191, 0.01739901452256877), ('hidden', 'cosine', 5): (0.40430463576158943, 0.04319639284872636), ('hidden_sigmoid', 'cosine', 200): (0.37682119205298015, 0.03389033530784983), ('hidden_sigmoid', 'asymcos', 200): (0.22483443708609274, 0.017266746470483402), ('hidden_sigmoid', 'cosine', 500): (0.29801324503311261, 0.025269416351422238)}, 20: {('decode', 'asymcos', 5): (0.015894039735099341, 0.0005693260905822896), ('hidden', 'cosine', 500): (0.36953642384105961, 0.033753312203989597), ('decode', 'asymcos', 200): (0.05066225165562914, 0.0024881686460818133), ('hidden_sigmoid', 'cosine', 5): (0.37384105960264902, 0.038338938216124184), ('hidden', 'cosine', 200): (0.38708609271523181, 0.034410425909013241), ('decode', 'asymcos', 500): (0.048675496688741722, 0.0028777555474772194), ('hidden', 'asymcos', 500): (0.069536423841059597, 0.003397251117226835), ('decode', 'cosine', 5): (0.42450331125827812, 0.045376044779644867), ('hidden', 'asymcos', 200): (0.029139072847682121, 0.0010506949600094029), ('hidden_sigmoid', 'asymcos', 5): (0.091721854304635766, 0.0060136763092525584), ('decode', 'cosine', 200): (0.36357615894039741, 0.03229493197647456), ('hidden', 'asymcos', 5): (0.0013245033112582781, 2.4471455006096599e-05), ('decode', 'cosine', 500): (0.32384105960264903, 0.028640448043775663), ('hidden_sigmoid', 'asymcos', 500): (0.42019867549668877, 0.036111954303831649), ('hidden', 'cosine', 5): (0.43013245033112585, 0.045736199532101396), ('hidden_sigmoid', 'cosine', 200): (0.35430463576158938, 0.031541114917292064), ('hidden_sigmoid', 'asymcos', 200): (0.41887417218543044, 0.038106149170784913), ('hidden_sigmoid', 'cosine', 500): (0.3208609271523179, 0.02617201864435478)}, 5: {('decode', 'asymcos', 5): (0.080132450331125843, 0.0043932010190209743), ('hidden', 'cosine', 500): (0.29768211920529802, 0.029128269882594607), ('decode', 'asymcos', 200): (0.18344370860927153, 0.013021838255424007), ('hidden_sigmoid', 'cosine', 5): (0.33410596026490069, 0.033837651355020912), ('hidden', 'cosine', 200): (0.33807947019867546, 0.031881780411132508), ('decode', 'asymcos', 500): (0.18013245033112585, 0.011826206786114546), ('hidden', 'asymcos', 500): (0.0, 0.0), ('decode', 'cosine', 5): (0.38609271523178806, 0.040789804272097371), ('hidden', 'asymcos', 200): (0.00033112582781456954, 1.8986572695789538e-06), ('hidden_sigmoid', 'asymcos', 5): (0.1119205298013245, 0.0063958224521917248), ('decode', 'cosine', 200): (0.35993377483443717, 0.035611960634400877), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.31192052980132451, 0.027362187808267779), ('hidden_sigmoid', 'asymcos', 500): (0.26026490066225166, 0.020769173906903946), ('hidden', 'cosine', 5): (0.39834437086092717, 0.042899526776910821), ('hidden_sigmoid', 'cosine', 200): (0.32913907284768212, 0.028092523007686082), ('hidden_sigmoid', 'asymcos', 200): (0.32251655629139075, 0.026882492631002352), ('hidden_sigmoid', 'cosine', 500): (0.276158940397351, 0.0218121175250333)}, 15: {('decode', 'asymcos', 5): (0.018543046357615892, 0.00061348439877666758), ('hidden', 'cosine', 500): (0.31688741721854308, 0.027711483746757824), ('decode', 'asymcos', 200): (0.047350993377483448, 0.0024849597995780085), ('hidden_sigmoid', 'cosine', 5): (0.36754966887417218, 0.036666558739426494), ('hidden', 'cosine', 200): (0.34271523178807944, 0.030280766503057343), ('decode', 'asymcos', 500): (0.0543046357615894, 0.0027853259020663435), ('hidden', 'asymcos', 500): (0.032781456953642388, 0.0013735862623084831), ('decode', 'cosine', 5): (0.42218543046357621, 0.044703244877262856), ('hidden', 'asymcos', 200): (0.0099337748344370865, 0.00046694616697775897), ('hidden_sigmoid', 'asymcos', 5): (0.070860927152317871, 0.0038849465894476021), ('decode', 'cosine', 200): (0.37052980132450331, 0.032712935483188314), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.30894039735099343, 0.027097628247914288), ('hidden_sigmoid', 'asymcos', 500): (0.40066225165562913, 0.035824390388427149), ('hidden', 'cosine', 5): (0.42880794701986757, 0.045053169496441281), ('hidden_sigmoid', 'cosine', 200): (0.36754966887417218, 0.034474129038475097), ('hidden_sigmoid', 'asymcos', 200): (0.39635761589403973, 0.036034705996876706), ('hidden_sigmoid', 'cosine', 500): (0.31225165562913909, 0.026107515741613546)}}), 5: ((0.12450331125827815, 0.0093878109537215253), {10: {('decode', 'asymcos', 5): (0.032450331125827819, 0.0011524367385721183), ('hidden', 'cosine', 500): (0.2867549668874172, 0.02674284813666138), ('decode', 'asymcos', 200): (0.067218543046357618, 0.0032705215513467545), ('hidden_sigmoid', 'cosine', 5): (0.35000000000000003, 0.035061499070888451), ('hidden', 'cosine', 200): (0.33476821192052986, 0.031096601623936321), ('decode', 'asymcos', 500): (0.073841059602649015, 0.0037131233174227431), ('hidden', 'asymcos', 500): (0.019867549668874173, 0.00049754824708098512), ('decode', 'cosine', 5): (0.40827814569536425, 0.042895577573777419), ('hidden', 'asymcos', 200): (0.0069536423841059609, 0.00021055166782992183), ('hidden_sigmoid', 'asymcos', 5): (0.024834437086092717, 0.0013675062868627602), ('decode', 'cosine', 200): (0.38079470198675502, 0.036211798393010156), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.34238410596026492, 0.030303878168686547), ('hidden_sigmoid', 'asymcos', 500): (0.21390728476821191, 0.01739901452256877), ('hidden', 'cosine', 5): (0.40430463576158943, 0.04319639284872636), ('hidden_sigmoid', 'cosine', 200): (0.37682119205298015, 0.03389033530784983), ('hidden_sigmoid', 'asymcos', 200): (0.22483443708609274, 0.017266746470483402), ('hidden_sigmoid', 'cosine', 500): (0.29801324503311261, 0.025269416351422238)}, 20: {('decode', 'asymcos', 5): (0.015894039735099341, 0.0005693260905822896), ('hidden', 'cosine', 500): (0.36953642384105961, 0.033753312203989597), ('decode', 'asymcos', 200): (0.05066225165562914, 0.0024881686460818133), ('hidden_sigmoid', 'cosine', 5): (0.37384105960264902, 0.038338938216124184), ('hidden', 'cosine', 200): (0.38708609271523181, 0.034410425909013241), ('decode', 'asymcos', 500): (0.048675496688741722, 0.0028777555474772194), ('hidden', 'asymcos', 500): (0.069536423841059597, 0.003397251117226835), ('decode', 'cosine', 5): (0.42450331125827812, 0.045376044779644867), ('hidden', 'asymcos', 200): (0.029139072847682121, 0.0010506949600094029), ('hidden_sigmoid', 'asymcos', 5): (0.091721854304635766, 0.0060136763092525584), ('decode', 'cosine', 200): (0.36357615894039741, 0.03229493197647456), ('hidden', 'asymcos', 5): (0.0013245033112582781, 2.4471455006096599e-05), ('decode', 'cosine', 500): (0.32384105960264903, 0.028640448043775663), ('hidden_sigmoid', 'asymcos', 500): (0.42019867549668877, 0.036111954303831649), ('hidden', 'cosine', 5): (0.43013245033112585, 0.045736199532101396), ('hidden_sigmoid', 'cosine', 200): (0.35430463576158938, 0.031541114917292064), ('hidden_sigmoid', 'asymcos', 200): (0.41887417218543044, 0.038106149170784913), ('hidden_sigmoid', 'cosine', 500): (0.3208609271523179, 0.02617201864435478)}, 5: {('decode', 'asymcos', 5): (0.080132450331125843, 0.0043932010190209743), ('hidden', 'cosine', 500): (0.29768211920529802, 0.029128269882594607), ('decode', 'asymcos', 200): (0.18344370860927153, 0.013021838255424007), ('hidden_sigmoid', 'cosine', 5): (0.33410596026490069, 0.033837651355020912), ('hidden', 'cosine', 200): (0.33807947019867546, 0.031881780411132508), ('decode', 'asymcos', 500): (0.18013245033112585, 0.011826206786114546), ('hidden', 'asymcos', 500): (0.0, 0.0), ('decode', 'cosine', 5): (0.38609271523178806, 0.040789804272097371), ('hidden', 'asymcos', 200): (0.00033112582781456954, 1.8986572695789538e-06), ('hidden_sigmoid', 'asymcos', 5): (0.1119205298013245, 0.0063958224521917248), ('decode', 'cosine', 200): (0.35993377483443717, 0.035611960634400877), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.31192052980132451, 0.027362187808267779), ('hidden_sigmoid', 'asymcos', 500): (0.26026490066225166, 0.020769173906903946), ('hidden', 'cosine', 5): (0.39834437086092717, 0.042899526776910821), ('hidden_sigmoid', 'cosine', 200): (0.32913907284768212, 0.028092523007686082), ('hidden_sigmoid', 'asymcos', 200): (0.32251655629139075, 0.026882492631002352), ('hidden_sigmoid', 'cosine', 500): (0.276158940397351, 0.0218121175250333)}, 15: {('decode', 'asymcos', 5): (0.018543046357615892, 0.00061348439877666758), ('hidden', 'cosine', 500): (0.31688741721854308, 0.027711483746757824), ('decode', 'asymcos', 200): (0.047350993377483448, 0.0024849597995780085), ('hidden_sigmoid', 'cosine', 5): (0.36754966887417218, 0.036666558739426494), ('hidden', 'cosine', 200): (0.34271523178807944, 0.030280766503057343), ('decode', 'asymcos', 500): (0.0543046357615894, 0.0027853259020663435), ('hidden', 'asymcos', 500): (0.032781456953642388, 0.0013735862623084831), ('decode', 'cosine', 5): (0.42218543046357621, 0.044703244877262856), ('hidden', 'asymcos', 200): (0.0099337748344370865, 0.00046694616697775897), ('hidden_sigmoid', 'asymcos', 5): (0.070860927152317871, 0.0038849465894476021), ('decode', 'cosine', 200): (0.37052980132450331, 0.032712935483188314), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.30894039735099343, 0.027097628247914288), ('hidden_sigmoid', 'asymcos', 500): (0.40066225165562913, 0.035824390388427149), ('hidden', 'cosine', 5): (0.42880794701986757, 0.045053169496441281), ('hidden_sigmoid', 'cosine', 200): (0.36754966887417218, 0.034474129038475097), ('hidden_sigmoid', 'asymcos', 200): (0.39635761589403973, 0.036034705996876706), ('hidden_sigmoid', 'cosine', 500): (0.31225165562913909, 0.026107515741613546)}}), 15: ((0.11920529801324503, 0.0080424451223021446), {10: {('decode', 'asymcos', 5): (0.032450331125827819, 0.0011524367385721183), ('hidden', 'cosine', 500): (0.2867549668874172, 0.02674284813666138), ('decode', 'asymcos', 200): (0.067218543046357618, 0.0032705215513467545), ('hidden_sigmoid', 'cosine', 5): (0.35000000000000003, 0.035061499070888451), ('hidden', 'cosine', 200): (0.33476821192052986, 0.031096601623936321), ('decode', 'asymcos', 500): (0.073841059602649015, 0.0037131233174227431), ('hidden', 'asymcos', 500): (0.019867549668874173, 0.00049754824708098512), ('decode', 'cosine', 5): (0.40827814569536425, 0.042895577573777419), ('hidden', 'asymcos', 200): (0.0069536423841059609, 0.00021055166782992183), ('hidden_sigmoid', 'asymcos', 5): (0.024834437086092717, 0.0013675062868627602), ('decode', 'cosine', 200): (0.38079470198675502, 0.036211798393010156), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.34238410596026492, 0.030303878168686547), ('hidden_sigmoid', 'asymcos', 500): (0.21390728476821191, 0.01739901452256877), ('hidden', 'cosine', 5): (0.40430463576158943, 0.04319639284872636), ('hidden_sigmoid', 'cosine', 200): (0.37682119205298015, 0.03389033530784983), ('hidden_sigmoid', 'asymcos', 200): (0.22483443708609274, 0.017266746470483402), ('hidden_sigmoid', 'cosine', 500): (0.29801324503311261, 0.025269416351422238)}, 20: {('decode', 'asymcos', 5): (0.015894039735099341, 0.0005693260905822896), ('hidden', 'cosine', 500): (0.36953642384105961, 0.033753312203989597), ('decode', 'asymcos', 200): (0.05066225165562914, 0.0024881686460818133), ('hidden_sigmoid', 'cosine', 5): (0.37384105960264902, 0.038338938216124184), ('hidden', 'cosine', 200): (0.38708609271523181, 0.034410425909013241), ('decode', 'asymcos', 500): (0.048675496688741722, 0.0028777555474772194), ('hidden', 'asymcos', 500): (0.069536423841059597, 0.003397251117226835), ('decode', 'cosine', 5): (0.42450331125827812, 0.045376044779644867), ('hidden', 'asymcos', 200): (0.029139072847682121, 0.0010506949600094029), ('hidden_sigmoid', 'asymcos', 5): (0.091721854304635766, 0.0060136763092525584), ('decode', 'cosine', 200): (0.36357615894039741, 0.03229493197647456), ('hidden', 'asymcos', 5): (0.0013245033112582781, 2.4471455006096599e-05), ('decode', 'cosine', 500): (0.32384105960264903, 0.028640448043775663), ('hidden_sigmoid', 'asymcos', 500): (0.42019867549668877, 0.036111954303831649), ('hidden', 'cosine', 5): (0.43013245033112585, 0.045736199532101396), ('hidden_sigmoid', 'cosine', 200): (0.35430463576158938, 0.031541114917292064), ('hidden_sigmoid', 'asymcos', 200): (0.41887417218543044, 0.038106149170784913), ('hidden_sigmoid', 'cosine', 500): (0.3208609271523179, 0.02617201864435478)}, 5: {('decode', 'asymcos', 5): (0.080132450331125843, 0.0043932010190209743), ('hidden', 'cosine', 500): (0.29768211920529802, 0.029128269882594607), ('decode', 'asymcos', 200): (0.18344370860927153, 0.013021838255424007), ('hidden_sigmoid', 'cosine', 5): (0.33410596026490069, 0.033837651355020912), ('hidden', 'cosine', 200): (0.33807947019867546, 0.031881780411132508), ('decode', 'asymcos', 500): (0.18013245033112585, 0.011826206786114546), ('hidden', 'asymcos', 500): (0.0, 0.0), ('decode', 'cosine', 5): (0.38609271523178806, 0.040789804272097371), ('hidden', 'asymcos', 200): (0.00033112582781456954, 1.8986572695789538e-06), ('hidden_sigmoid', 'asymcos', 5): (0.1119205298013245, 0.0063958224521917248), ('decode', 'cosine', 200): (0.35993377483443717, 0.035611960634400877), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.31192052980132451, 0.027362187808267779), ('hidden_sigmoid', 'asymcos', 500): (0.26026490066225166, 0.020769173906903946), ('hidden', 'cosine', 5): (0.39834437086092717, 0.042899526776910821), ('hidden_sigmoid', 'cosine', 200): (0.32913907284768212, 0.028092523007686082), ('hidden_sigmoid', 'asymcos', 200): (0.32251655629139075, 0.026882492631002352), ('hidden_sigmoid', 'cosine', 500): (0.276158940397351, 0.0218121175250333)}, 15: {('decode', 'asymcos', 5): (0.018543046357615892, 0.00061348439877666758), ('hidden', 'cosine', 500): (0.31688741721854308, 0.027711483746757824), ('decode', 'asymcos', 200): (0.047350993377483448, 0.0024849597995780085), ('hidden_sigmoid', 'cosine', 5): (0.36754966887417218, 0.036666558739426494), ('hidden', 'cosine', 200): (0.34271523178807944, 0.030280766503057343), ('decode', 'asymcos', 500): (0.0543046357615894, 0.0027853259020663435), ('hidden', 'asymcos', 500): (0.032781456953642388, 0.0013735862623084831), ('decode', 'cosine', 5): (0.42218543046357621, 0.044703244877262856), ('hidden', 'asymcos', 200): (0.0099337748344370865, 0.00046694616697775897), ('hidden_sigmoid', 'asymcos', 5): (0.070860927152317871, 0.0038849465894476021), ('decode', 'cosine', 200): (0.37052980132450331, 0.032712935483188314), ('hidden', 'asymcos', 5): (0.00033112582781456954, 1.8986572695789538e-06), ('decode', 'cosine', 500): (0.30894039735099343, 0.027097628247914288), ('hidden_sigmoid', 'asymcos', 500): (0.40066225165562913, 0.035824390388427149), ('hidden', 'cosine', 5): (0.42880794701986757, 0.045053169496441281), ('hidden_sigmoid', 'cosine', 200): (0.36754966887417218, 0.034474129038475097), ('hidden_sigmoid', 'asymcos', 200): (0.39635761589403973, 0.036034705996876706), ('hidden_sigmoid', 'cosine', 500): (0.31225165562913909, 0.026107515741613546)}})}

In [8]:
t = tmp.values()


In [11]:
pprint(tmp)

{5: ((0.12450331125827815, 0.009387810953721525),
     {5: {('decode', 'asymcos', 5): (0.08013245033112584,
                                     0.004393201019020974),
          ('decode', 'asymcos', 200): (0.18344370860927153,
                                       0.013021838255424007),
          ('decode', 'asymcos', 500): (0.18013245033112585,
                                       0.011826206786114546),
          ('decode', 'cosine', 5): (0.38609271523178806,
                                    0.04078980427209737),
          ('decode', 'cosine', 200): (0.35993377483443717,
                                      0.03561196063440088),
          ('decode', 'cosine', 500): (0.3119205298013245,
                                      0.02736218780826778),
          ('hidden', 'asymcos', 5): (0.00033112582781456954,
                                     1.8986572695789538e-06),
          ('hidden', 'asymcos', 200): (0.00033112582781456954,
                                       1.898657269